### ISSUE TITLE
Hi sir

### ISSUE THREAD

**Issue by KevinMagnifico260** [raysan5/raygui#100]
It is possible to make multiple Window in Raygui sir

**Comment by raysan5** [comment]
@KevinMagnifico260 hi, if you mean multiple separate windows, it's not possible at the moment. But you can create multiple GuiWindow() inside the main program window.

**Comment by KevinMagnifico260** [comment]
thank you for your advice sir
    On Sunday, July 12, 2020, 09:04:22 PM GMT+8, Ray <notifications@github.com> wrote:  
 
 


@KevinMagnifico260 hi, if you mean multiple separate windows, it's not possible at the moment. But you can create multiple GuiWindow() inside the main program window.
