### ISSUE TITLE
Hardcoded GetMousePosition

### ISSUE THREAD

**Issue by muevoid** [raysan5/raygui#101]
I was planning on using this for an application that I am working on that uses a virtual mouse position due to the window being scaled. However since GetMousePosition is hardcoded there is no way to pass my virtualMouse vector2.

**Comment by muevoid** [comment]
Nevermind I am closing this as I am stupid and did not realize there is a SetMousePosition Function.

**Comment by muevoid** [comment]
Still not sure how exactly how to do this actually. As SetMousePosition physically moves the cursor.

**Comment by muevoid** [comment]
It was quite a simple fix. I made a function in raygui.h called GuiSetMousePos(Vector2 mouse) which would be udpated every frame outside of raygui.h in the gameloop/programloop with the vector2 you would like to use. If you were using a normal mouse of course MouseGetPosition would be fine. If this is something that you would like to see in raygui I could open up a pull request.

**Comment by raysan5** [comment]
@muevoid the solution I use on my tools is just getting the mouse position and scaling+offseting it properly for scaled window.
