### ISSUE TITLE
is there a way to get the focus status?

### ISSUE THREAD

**Issue by xdrie** [raysan5/raygui#104]
is there a way i can check whether a particular `GuiTextBox` is focused?

**Comment by raysan5** [comment]
@xdrie Actually, with the current implementation the editMode state variable sets the focus status for editing.

**Comment by xdrie** [comment]
Doesn't that variable just set whether it's editable? I want to know which of my textboxes are focused in a function that draws a bunch of them, is that currently possible?

Thanks!

**Comment by raysan5** [comment]
@xdrie setting a `GuiTextBox()` as editable is managed by user, you are responsible to detect and set the editable one checking the status of the other ones. You can check `controls_test_suite`, there are several editable textboxes and you can check from one to the other... to know the one that is active, just check the `editMode` of all them to see the one that is active.

**Comment by xdrie** [comment]
Thank you very much! I really appreciate the time you took to write up a detailed answer.
