### ISSUE TITLE
Where do I call GuiLoadStyle()?

### ISSUE THREAD

**Issue by ZaneL** [raysan5/raygui#105]
I'm trying to test out some of the custom styles, but for some reason all I can get raylib to do is to load the default style.

I've tried placing GuiLoadStyle("candy/candy.rgs"); all over the place but it doesn't seem to load the style regardless of what I do. I have both the rgs file and the associated font in a folder called candy and that folder is in my project directory.

**Comment by MNAJIM75** [comment]
you need to call it after the InitWindow() function
`int main (void)
{
    const int screenWidth = 800; // width of screen
    const int screenHeight = 450; // height of screen

    InitWindow( screenWidth, screenHeight, "Game Title"); // Creates a Window
    GuiLoadStyle("styles\\candy\\candy.rgs");
}`

**Comment by raysan5** [comment]
@MNAJIM75 that's it.
@ZaneL It should work just calling `GuiLoadStyle()` after `InitWindow()`, you can also try placing `candy.rgs` in the same directory as your executable.
