### ISSUE TITLE
How to include raygui.h in multiple files other than main.c

### ISSUE THREAD

**Issue by MNAJIM75** [raysan5/raygui#108]
Hello.

I'm trying to make custom controls. So i created a control.c and control.h just to test and i added the following lines to control.c and main.c :
`#define RAYGUI_IMPLEMENTATION`
`#include "raygui.h"`
But when i compile, i get errors with no error message.
so i saw this [Issue](https://github.com/raysan5/raygui/issues/62) and i tried to add `#define RAYGUI_STATIC` instead of `#define RAYGUI_IMPLEMENTATION` in the control.c file but nothing seems to be working.

Some example would be nice.

Thanks.

**Comment by raysan5** [comment]
@MNAJIM75 `RAYGUI_IMPLEMENTATION` only have to be defined in one module. If it is eaiser for you, just split `raygui.h` into `raygui.h` and `raygui.c`.

**Comment by atakhan** [comment]
> @MNAJIM75 `RAYGUI_IMPLEMENTATION` only have to be defined in one module. If it is eaiser for you, just split `raygui.h` into `raygui.h` and `raygui.c`.

thanks, it works
