### ISSUE TITLE
GuiButtons in GuiGroupbox are not clickeable

### ISSUE THREAD

**Issue by Darksw20** [raysan5/raygui#112]
Hi! Im trying to do a HUD for my game using raygui, but when I try to click the GuiButtons it doesnt detect the event. They render correctly but seems imposible to make it work. I used the same buttons in another screens but the buttons work correctly there. Someone can help me?

![image](https://user-images.githubusercontent.com/30423633/101125737-91701700-35bf-11eb-9544-a8b374835733.png)
Image of the actual Game.

The code of that window is:

```
case GAME:
         BeginMode2D(game->board->camera);
             DrawTexture(game->board->mapBackground, 0, 0, WHITE);
             DrawTexture(game->board->map, 0, 0, WHITE);
             MovementInBoard(game);
             
             int initXHUD = (int)((game->board->camera.target.x)-960);
             int initYHUD = (int)((game->board->camera.target.y)+270);
             DrawRectangle(initXHUD,initYHUD,game->screenWidth,game->screenHeight/4,DARKGRAY);
                        
             GuiGroupBox((Rectangle){ initXHUD + 25, initYHUD + 30, 125, 150 }, "OPTIONS");
             if (GuiButton((Rectangle){ initXHUD + 30, initYHUD + 40, 115, 30 }, "Tirar Dado")) {
                    fprintf(stdout,"Hola");
              }
              if (GuiButton((Rectangle){ initXHUD + 30, initYHUD + 75, 115, 30 }, "Suggest")) { 
                    fprintf(stdout,"Hola");
               }
              if (GuiButton((Rectangle){ initXHUD + 30, initYHUD + 110, 115, 30 }, "Notebook")) {
                    fprintf(stdout,"Hola");
               }
           EndMode2D();    
           break;

```
The unique thing that is diferent from the other screens is the use of BeginMode2D. I dont know if that is something worth to say.  Also I tried some other elements like GuiDropdownBox and didnt work neither.

**Comment by raysan5** [comment]
It seems that the `Camera2D` transformations applied by `BeginMode2D()` do not apply to GUI elements input, only applied to drawing, so GUI elements are drawn in a different position than the one checked.

To solve that you should use raylib functions: `SetMouseScale()` and `SetMouseOffset()` to apply the same transformation to mouse input than the one applied by `Camera2D`.

**Comment by mikaelssen** [comment]
> It seems that the `Camera2D` transformations applied by `BeginMode2D()` do not apply to GUI elements input, only applied to drawing, so GUI elements are drawn in a different position than the one checked.
> 
> To solve that you should use raylib functions: `SetMouseScale()` and `SetMouseOffset()` to apply the same transformation to mouse input than the one applied by `Camera2D`.

If people like me see this in the future, Ray should probably put a fix in for it, but here's what ray basically means.
This code works specifically for C# but should be really easy to translate to anything else.

```csharp
Raylib.SetMouseOffset((int)camera.target.X, (int)camera.target.Y);
Raylib.SetMouseScale(camera.zoom,camera.zoom);

```
