### ISSUE TITLE
invalid use of BUILD_LIBTYPE_SHARED in src/raygui.h + zoom factor

### ISSUE THREAD

**Issue by brechtsanders** [raysan5/raygui#117]
In `src/raygui.h` `RAYGUIDEF` should be defined as `__declspec(dllexport)` if `BUILD_LIBTYPE_SHARED` is defined, but the code now does it if `BUILD_LIBTYPE_SHARED` is not defined. I think this is a mistake. The following patch fixes it:
```
patch -ulbf src/raygui.h << EOF
@@ -141,3 +141,3 @@
     // Microsoft attibutes to tell compiler that symbols are imported/exported from a .dll
-    #if !defined(BUILD_LIBTYPE_SHARED)
+    #if defined(BUILD_LIBTYPE_SHARED)
         #define RAYGUIDEF __declspec(dllexport)     // We are building raygui as a Win32 shared library (.dll)
EOF
```

Also, I'm using a 4k display on Windows 10 with zoom factor set to 200%. Is there any chance raygui could zoom accordingly? Now everything is super small...

**Comment by raysan5** [comment]
Ouch! Thanks! Good catch! It was updated some days ago and the error introduced!
