### ISSUE TITLE
Resolution independent layout system is missing

### ISSUE THREAD

**Issue by zzador** [raysan5/raygui#119]
While I thought this would not be necessary I encountered now some problems that arise from fixed resolution GUI layouts. For example the app "rGuiLayout" is unusable on two of my laptops that have a max display resolution of 1366x768. The window is just to big and the app is completely unusable for me therefore. I would propose a very simple hierarchical layout scheme like FlexBox from CSS or the BoxLayout from Java. I haven't seen a layout to this day that could not be realized with flexbox.

**Comment by raysan5** [comment]
@zzador I'm afraid this is out-of-scope for this project. I recommend using DearImgui instead.
