### ISSUE TITLE
Include guard issues with C++

### ISSUE THREAD

**Issue by lolleko** [raysan5/raygui#120]
```cpp
#if defined(__cplusplus)
extern "C" {            // Prevents name mangling of functions
#endif
```
https://github.com/raysan5/raygui/blob/master/src/raygui.h#L177

is defined inside the "include guard block":

https://github.com/raysan5/raygui/blob/master/src/raygui.h#L130 - https://github.com/raysan5/raygui/blob/master/src/raygui.h#L502
```cpp
#ifndef RAYGUI_H
#define RAYGUI_H
...
#endif
```

The closing brace for `extern C` however is defined outside the guard block
https://github.com/raysan5/raygui/blob/master/src/raygui.h#L3721
```cpp
#if defined(__cplusplus)
}            // Prevents name mangling of functions
#endif
```

=>

```cpp
#ifndef RAYGUI_H
#define RAYGUI_H

#if defined(__cplusplus)
extern "C" {            // Prevents name mangling of functions
#endif

...

#endif // RAYGUI_H

...

#if defined(__cplusplus)
}            // Prevents name mangling of functions
#endif
```
Therefore if you add the raygui header more than once in a c++ project you will get an extraneous brace and will be unable to compile.

Any reason why the include guard block ends on line 502 instead of the end of the file?

**Comment by raysan5** [comment]
@lolleko that guard was just reviewed some days ago, it was probably an error... Feel free to send a PR with the fix.
