### ISSUE TITLE
GuiToggle() weird behavior

### ISSUE THREAD

**Issue by ZaneL** [raysan5/raygui#124]
When you click on a GuiToggle button it changes colors incorrectly.

Right now it goes like this:
Mouse over (light blue) -> Click (dark blue) -> Goes back to light blue -> Move mouse off of the button (goes to dark blue)

How it should work (imo):
Mouse over (light blue) -> Click (dark blue)

**Comment by Julianiolo** [comment]
@ZaneL whats the difference?

**Comment by raysan5** [comment]
I think it's consistent with the behaviour of all the other controls.
