### ISSUE TITLE
Using RayGUI with Existing GLFW Context

### ISSUE THREAD

**Issue by IndianBoy6** [raysan5/raygui#126]
Hi. I saw raygui and it looks pretty cool but I already have a game running using GLFW/GLAD. Is there a way I can use the window with RayGUI without having to create it through the raylib API?

**Comment by raysan5** [comment]
@IndianBoy6 `raygui` can be used as standalone if required functions are provided by user, just check `RAYGUI_STANDALONE` define for required functions. Check `examples/standalone/raygui_standalone.c` for some reference.
