### ISSUE TITLE
GuiProgressBar bug

### ISSUE THREAD

**Issue by Lightnet** [raysan5/raygui#128]
I notice the progress bar was not working. The int to float help make it work.
raygui.h

`if (state != GUI_STATE_DISABLED) progress.width = ((int)(value/(maxValue - minValue))*(float)(bounds.width - 2*GuiGetStyle(PROGRESSBAR, BORDER_WIDTH)));`

`if (state != GUI_STATE_DISABLED) progress.width = ((float)(value/(maxValue - minValue))*(float)(bounds.width - 2*GuiGetStyle(PROGRESSBAR, BORDER_WIDTH)));`

**Comment by raysan5** [comment]
@Lightnet Thanks! Reviewed!
