### ISSUE TITLE
[tool] rGuiLayout: crash due to path length too short

### ISSUE THREAD

**Issue by joeld42** [raysan5/raygui#13]
in `rguilayout.c` line 1767 in ShowSaveLayoutDialog, outFileName is length 64, this causes a crash when saving to path longer than that. Suggest using MAX_PATH or something like that. Also similar issue in ShowExportLayoutDialog

**Comment by raysan5** [comment]
hey @joeld42! thanks for reporting! I'll change that ASAP!

**Comment by raysan5** [comment]
corrected. rGuiLayout moved to [own repo](https://github.com/raysan5/rguilayout).
