### ISSUE TITLE
rGuiStyler candy style's font doesn't support >

### ISSUE THREAD

**Issue by Shylie** [raysan5/raygui#133]
the > character isn't supported by the [font bundled with the candy style](https://www.dafont.com/v5eastergothic.font) from rGuiStyler
![image](https://user-images.githubusercontent.com/28541112/116440449-85128200-a81e-11eb-9fe4-d6ece51cc38e.png)

**Comment by raysan5** [comment]
Ouch! It looks like a bug! :P

**Comment by raysan5** [comment]
Unfortunately, I'm afraid this issue is out of my control, it's related to the font.
