### ISSUE TITLE
Loading Custom Styles Causes SegFault

### ISSUE THREAD

**Issue by OkiStuff** [raysan5/raygui#138]
# Version
First Tried on RayGUI v2.6, Then tried just using the master branch. Both caused a seg fault
# Problem
Using GuiLoadStyle() causes seg faults in two locations:
 - If it has a custom font, It crashes/seg faults at line 2790
 - If it does not use a custom font, It crahses/seg faults at line 3177

# Notice
I am using a raylib wrapper, but all this wrapper does is give a separate update function,but It does not affect how raylib is being used at all. And yes it is in C
# Code
```c
#define RAYGUI_IMPLEMENTATION
#define RAYGUI_SUPPORT_ICONS
#define SCREEN_WIDTH 1280
#define SCREEN_HEIGHT 720
#include <Muzzle.h> //raylib wrapper
#include "raygui/raygui.h"

void OnAppletUpdate()
{
    while (IsAppletAlive()) //IsAppletAlive() returns !WindowShouldClose()
    {
        BeginDrawing();
            ClearBackground(RAYWHITE);
            if(GuiButton((Rectangle){0,0,50,50}, "Test"))
            {
                SetWindowTitle("Muzzle Editor [ALPHA] - Test");
            }
        EndDrawing();
    }
    
}

int main(void)
{
    
    Applet editor = InitalizeApplet(SCREEN_WIDTH, SCREEN_HEIGHT, 60, "Muzzle Editor [ALPHA] - No Projects Loaded"); // Initalizes Raylib

    GuiLoadStyle("styles/gray/gray.rgs");
    StartApplet(&editor); // runs Update Function
    

    QuitMuzzle();
    return 0;
}
```

I have tried Loading the style before raylib is initialized (It gets initialized in InitalizeApplet()). Same problem
And I have tried with just using raylib with no wrapper. I get the same issue

**Comment by OkiStuff** [comment]
Another note, In the code above I was trying to use a custom style that uses no custom font. But any style I try doesn't work.

**Comment by wintermute-cell** [comment]
Hey, I am experiencing the same problem, and as the original report did not provide further insight I am not sure whether it's user error or a bug (maybe due to the 4.0-dev changes).

The problem appears both when using an imported header and when using `GuiLoadStyle()` on the `.rgs`.

The version is: `raygui v4.0-dev`

Here is a Stacktrace:
```
0x0000000000000000 in ?? ()
0x0000555555586b2c in rlLoadTexture (data=0x7ffff35ff010, width=256, height=256, format=2, mipmapCount=1) at /home/wintermute/src/weary-rl/vendor/raylib/src/rlgl.h:2941
0x00005555555ebb40 in LoadTextureFromImage (image=...) at /home/wintermute/src/weary-rl/vendor/raylib/src/rtextures.c:3340
0x000055555556d47a in GuiLoadStyleJungle () at /home/wintermute/src/weary-rl/vendor/raygui/styles/jungle/jungle.h:317
0x000055555557659d in init () at /home/wintermute/src/weary-rl/main.c:33
0x0000555555576647 in main () at /home/wintermute/src/weary-rl/main.c:45
```

and here is the corresponding code (with omissions for brevity):
```c

#include "raylib.h"
#define RAYGUI_IMPLEMENTATION
#include "raygui.h"
#undef RAYGUI_IMPLEMENTATION

void init() {
    GuiLoadStyle("../endor/raygui/styles/jungle/jungle.rgs");
    InitWindow(1280, 720, "raylib window");
    SetTargetFPS(30);
}

int main(void)
{
    init();

    // game loop, etc...
}
```

**Comment by raysan5** [comment]
@wintermute-cell GuiLoadStyle() should be called after InitWindow(), OpenGL context must be initialized to load the font texture

**Comment by wintermute-cell** [comment]
Thank you, this was the problem!
