### ISSUE TITLE
[tool] rGuiLayout: When layout has controls underneath control selector, the underlying controls are manipulated too

### ISSUE THREAD

**Issue by triplefox** [raysan5/raygui#14]
In the attached screenshot you can see an example: 
![example_underneath](https://user-images.githubusercontent.com/1550842/44135572-70ae5f4c-a01e-11e8-9573-c47fd1356e52.png)

I tried to select "Button" and it also selected the button placed underneath.

**Comment by raysan5** [comment]
This behaviour can be controlled now by user using `GuiLock()` and `GuiUnlock()` functions. rGuiLayout tool moved to [own repo](https://github.com/raysan5/rguilayout).
