### ISSUE TITLE
Compiling as a shared library on Linux (documentation)

### ISSUE THREAD

**Issue by weskerfoot** [raysan5/raygui#146]
Currently, in order to get it working as a shared library on Linux (which, e.g. is necessary if you want to use it with https://github.com/Guevara-chan/Raylib-Forever or things like Python/Lua/etc), you need to do something like the following

`mv src/raygui.h src/raygui.c && gcc -shared -fpic -DRAYGUI_SUPPORT_ICONS -DRAYGUI_IMPLEMENTATION -lraylib -lGL -lm -lpthread -ldl -lrt -lX11 src/raygui.c -o raygui.so`

It would be useful if it were documented somewhere, or built into the Makefile, since it took me a while to figure out that GCC behaves differently if you give it a .h file vs a .c file, and doesn't give any visible warnings that it won't work (i.e. `nm -D raygui.so` won't list the correct symbols if you compile it as a .h file).

**Comment by raysan5** [comment]
@weskerfoot Just added a note in the README.md.
