### ISSUE TITLE
Compiling/Linking errors

### ISSUE THREAD

**Issue by Skips75** [raysan5/raygui#147]
Hi,

cloned the master branch (`78f24a3`) and in `example` directory after issued the
command `make PLATFORM=PLATFORM_DESKTOP` I got the following errors:

In file included from **`text_box_selection/textbox_extended_demo.c:33:
text_box_selection/../../src/gui_textbox_extended.h:`** In function **`'GuiTextBoxGetByteIndex':
text_box_selection/../../src/gui_textbox_extended.h:207:22:`** warning: implicit declaration of function **`'GetNextCodepoint'`**; did you mean **`'GetPrevCodepoint'?`** [-Wimplicit-function-declaration]

`207 | int letter = GetNextCodepoint(&text[i], &j);`

Tools used to build the example projects:

* gcc --version:

`
gcc.exe (GCC) 9.2.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
`

* make --version:

`
GNU Make 4.3
Built for Windows32
Copyright (C) 1988-2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
`

Consequently the compiler issued the error:

`
d:/scoopapp/apps/nuwen-mingw-gcc/current/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\stefano\AppData\Local\Temp\ccih0Ndd.o:textbox_extended_demo.c:(.text+0xcb98): undefined reference to `GetNextCodepoint'
`

**Comment by weskerfoot** [comment]
I'm guessing you don't have raylib installed as a shared library / dll already

**Comment by raysan5** [comment]
@Skips75 that function was renamed in raylib 3.8-dev, just updated it.
