### ISSUE TITLE
[tool] rGuiLayout: when two controls overlap and one is deleted, program is no longer able to select controls

### ISSUE THREAD

**Issue by triplefox** [raysan5/raygui#15]
As in screenshot: 
![overlap](https://user-images.githubusercontent.com/1550842/44136860-391fd510-a023-11e8-8731-f4569a071729.png)

**Comment by raysan5** [comment]
Hey @triplefox! Thank you very much for reporting those issues!

Did you like the tool? Please, could you give me some feedback? Thanks! :)

**Comment by triplefox** [comment]
Feedback? Well, I just used it to put together a kind of mockup. 

![platfxrmock](https://user-images.githubusercontent.com/1550842/44142304-ab2c0ad2-a034-11e8-9fb1-3eadb981e52e.png)

I want to do a tool like SFXR using this [modular synth oscillator](https://mutable-instruments.net/modules/plaits/) as a basis(the company releases the code of their modules as open-source a few months after they sell their first run). So I thought I would see how it would look if I used raygui.

rGuiLayout seems to work well at least for the mockup part, the basic idea of it feels right although you can tell I did a few image edits to label things, and with the bugs I encountered, I had to save and restart several times. There are more bugs than the ones I reported, I think, those are just the ones I could easily reproduce. I found the anchor system confusing - is it meant to work for all types of controls or only some of them?

**Comment by raysan5** [comment]
`rGuiLayout` has been moved to its [own repo](https://github.com/raysan5/rguilayout) and it's being hardly reviewed. Just closing this issue.
