### ISSUE TITLE
rGuiIcons header export

### ISSUE THREAD

**Issue by ProkopRandacek** [raysan5/raygui#152]
Hi,
I'm not sure where to put this issue since I didn't find rGuiIcons github repo.

There is noted in the source code of raygui that rGuiIcons can generate a custom ricons header file that can be included by raygui.
https://github.com/raysan5/raygui/blob/master/src/raygui.h#L531
But I can't find other exports than `.rgi` and `.png`. Where can I generate the header file?

**Comment by raysan5** [comment]
@ProkopRandacek Actually the `.h` export feature is only available on version `ONE` (the paid one)... but I changed that for next release, hopefully by the end of this month.
