### ISSUE TITLE
Used, But Not Defined

### ISSUE THREAD

**Issue by wwderw** [raysan5/raygui#153]
Just found this wonderful library (both raylib and this one) and while I'm doing OK within raylib, I seem to be having a problem with getting gui elements to work.  They all appear to have a "used, but not defined" issue.

Using stable releases for raylib and raygui (tried latest, but was actually having other issues, made further progress with stable, so been sticking with that).

I had started with:
#include "include/raylib.h"
#define RAYGUI_IMPLEMENTATION
#include "include/raygui.h"
#undef RAYGUI_IMPLEMENTATION 

But that didn't work with getting anything to show up in my IDE, so tried this:
#include "include/raylib.h"
#define RAYGUI_STATIC
#include "include/raygui.h"
#undef RAYGUI_STATIC

And that seemed to have satisfied my IDE and as long as I don't use any raygui specifics, the compiler is happy as well.  However, if I use anything that is specific to raygui, the compiler starts to get angry with me.

I'm sure that it's something that I am not doing, but I am at a lost and I haven't seen anything else in the samples, unless I just missed it (which is quite possible).

Any thoughts?  Thanks!

Loving raylib.  It's taking me awhile (having come from Godot as far as games go), but would like to be able to use this for applications as well.

**Comment by raysan5** [comment]
@wwderw Are you using latest raygui from GitHub master branch? `RAYGUI_STATIC` does not exist any more...

Actually, it should be enough including:
```c
#include "raylib.h"

#define RAYGUI_IMPLEMENTATION
#define RAYGUI_SUPPORT_RICONS
#include "../../src/raygui.h"

#undef RAYGUI_IMPLEMENTATION            // Avoid including raygui implementation again
```

It works for all my tools in multiple platforms.

What platform and IDE are you using?

**Comment by wwderw** [comment]
I'm actually using an official release for raylib and raygui (official as in in the release section), using the latest raygui from master did not work.

Using the latest official release from raygui, I was only able to get the #include accepted, atleast as far as the IDE goes, with STATIC.

This is using Neon with VSCode (using the C/C++ extension).  Also have a VM for Windows using the latest official binary for raylib as well, but I start with Linux and then just use the VM for a Windows build.

**Comment by raysan5** [comment]
I'm afraid you should use latest raylib and latest raygui from github master branch. The versions you are using are outdated.

**Comment by wwderw** [comment]
Ok, Ill spin up a VM and see if there is something that I missed when I was compiling when I originally tried it.  

Thanks!

**Comment by wwderw** [comment]
Using the latest of both raylib and raygui including the raygui.h file in above manner, I get this in the terminal:

`In file included from main.cpp:6:
include/raygui.h: In function ‘void GuiGroupBox(Rectangle, const char*)’:
include/raygui.h:1391:182: warning: enumeral mismatch in conditional expression: ‘GuiControlProperty’ vs ‘GuiDefaultProperty’ [-Wenum-compare]
 1391 |     GuiDrawRectangle(RAYGUI_CLITERAL(Rectangle){ bounds.x, bounds.y, GROUPBOX_LINE_THICK, bounds.height }, 0, BLANK, Fade(GetColor(GuiGetStyle(DEFAULT, (state == GUI_STATE_DISABLED)? BORDER_COLOR_DISABLED : LINE_COLOR)), guiAlpha));
      |                                                                                                                                                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
include/raygui.h:1392:201: warning: enumeral mismatch in conditional expression: ‘GuiControlProperty’ vs ‘GuiDefaultProperty’ [-Wenum-compare]
 1392 |     GuiDrawRectangle(RAYGUI_CLITERAL(Rectangle){ bounds.x, bounds.y + bounds.height - 1, bounds.width, GROUPBOX_LINE_THICK }, 0, BLANK, Fade(GetColor(GuiGetStyle(DEFAULT, (state == GUI_STATE_DISABLED)? BORDER_COLOR_DISABLED : LINE_COLOR)), guiAlpha));
      |                                                                                                                                                                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
include/raygui.h:1393:201: warning: enumeral mismatch in conditional expression: ‘GuiControlProperty’ vs ‘GuiDefaultProperty’ [-Wenum-compare]
 1393 |     GuiDrawRectangle(RAYGUI_CLITERAL(Rectangle){ bounds.x + bounds.width - 1, bounds.y, GROUPBOX_LINE_THICK, bounds.height }, 0, BLANK, Fade(GetColor(GuiGetStyle(DEFAULT, (state == GUI_STATE_DISABLED)? BORDER_COLOR_DISABLED : LINE_COLOR)), guiAlpha));
      |                                                                                                                                                                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
include/raygui.h: In function ‘void GuiLine(Rectangle, const char*)’:
include/raygui.h:1406:83: warning: enumeral mismatch in conditional expression: ‘GuiControlProperty’ vs ‘GuiDefaultProperty’ [-Wenum-compare]
 1406 |     Color color = Fade(GetColor(GuiGetStyle(DEFAULT, (state == GUI_STATE_DISABLED)? BORDER_COLOR_DISABLED : LINE_COLOR)), guiAlpha);
      |                                                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
include/raygui.h: In function ‘void GuiPanel(Rectangle)’:
include/raygui.h:1436:114: warning: enumeral mismatch in conditional expression: ‘GuiControlProperty’ vs ‘GuiDefaultProperty’ [-Wenum-compare]
 1436 |     GuiDrawRectangle(bounds, PANEL_BORDER_WIDTH, Fade(GetColor(GuiGetStyle(DEFAULT, (state == GUI_STATE_DISABLED)? BORDER_COLOR_DISABLED: LINE_COLOR)), guiAlpha),
      |                                                                                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
include/raygui.h:1437:86: warning: enumeral mismatch in conditional expression: ‘GuiControlProperty’ vs ‘GuiDefaultProperty’ [-Wenum-compare]
 1437 |                      Fade(GetColor(GuiGetStyle(DEFAULT, (state == GUI_STATE_DISABLED)? BASE_COLOR_DISABLED : BACKGROUND_COLOR)), guiAlpha));
      |                                                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/bin/ld: /tmp/ccTo36g2.o: in function `GuiTextBox':
main.cpp:(.text+0x438b): undefined reference to `CodepointToUTF8'
/usr/bin/ld: /tmp/ccTo36g2.o: in function `GuiTextBoxMulti':
main.cpp:(.text+0x57a8): undefined reference to `CodepointToUTF8'
/usr/bin/ld: main.cpp:(.text+0x5b5d): undefined reference to `GetCodepoint'
/usr/bin/ld: /tmp/ccTo36g2.o:(.data.rel.local.DW.ref.__gxx_personality_v0[DW.ref.__gxx_personality_v0]+0x0): undefined reference to `__gxx_personality_v0'
collect2: error: ld returned 1 exit status`

**Comment by raysan5** [comment]
@wwderw It seems your compiler issues some warnings. Also, about `undefined reference to CodepointToUTF8 and GetCodepoint`, are you using latest raylib? Those functions were renamed some weeks ago.

**Comment by wwderw** [comment]
I followed the instructions in the wiki for compiling from source for Linux.  Also using the make version versus cmake as far as instruction set goes.
