### ISSUE TITLE
Confusing click triggering

### ISSUE THREAD

**Issue by ProkopRandacek** [raysan5/raygui#154]
Hello,
Elements can be clicked even if they are cropped away with the `BeginScissorMode` / `EndScissorMode` functions and in general things can be clicked even if there is another element drawn over them.

Is there a plan to fix these issues or am I supposed to handle it on my side?

**Comment by raysan5** [comment]
@ProkopRandacek I'm afraid I'm avoiding scissoring in raylib library so, it's up to the user to manage the consequences of using it.

There is `GuiLock()` and `GuiUnlock()` functions provided to manage it from user side but at this moment there is a small issue with those functions when using `GuiComboBox()` #139.
