### ISSUE TITLE
latest version has problems

### ISSUE THREAD

**Issue by ejamshidiasl** [raysan5/raygui#157]
Hi, i downloaded repo as .zip but there is no raycons.h file in src folder and when i include and use raygui.h i get these errors:
(but replacing raygui.h with latest release (2019) works)

`C:\Users\arman\Documents\vsCode\test\req/raygui.h:2398:21: error: 'glyphInfo' was not declared in this scope
 2398 |                 if (glyphInfo.advanceX != 0) glyphWidth += glyphInfo.advanceX;
      |                     ^~~~~~~~~
C:\Users\arman\Documents\vsCode\test\req/raygui.h:2431:17: error: 'glyphInfo' was not declared in this scope
 2431 |             if (glyphInfo.advanceX != 0) glyphWidth += glyphInfo.advanceX;
      |                 ^~~~~~~~~
C:\Users\arman\Documents\vsCode\test\req/raygui.h: In function 'void GuiLoadStyle(const char*)':
C:\Users\arman\Documents\vsCode\test\req/raygui.h:3420:60: error: 'Font' {aka 'struct Font'} has no member named 'glyphCount'
 3420 |                         if ((font.texture.id > 0) && (font.glyphCount > 0)) GuiSetFont(font);    
      |                                                            ^~~~~~~~~~
C:\Users\arman\Documents\vsCode\test\req/raygui.h:3490:29: error: 'Font' {aka 'struct Font'} has no member named 'glyphCount'
 3490 |                 fread(&font.glyphCount, 1, sizeof(int), rgsFile);
      |                             ^~~~~~~~~~
In file included from C:\Users\arman\Documents\vsCode\test\main.cpp:5:
C:\Users\arman\Documents\vsCode\test\req/raygui.h:3517:61: error: 'Font' {aka 'struct Font'} has no member named 'glyphCount'
 3517 |                 font.recs = (Rectangle *)RAYGUI_CALLOC(font.glyphCount, sizeof(Rectangle));      
      |                                                             ^~~~~~~~~~
C:\Users\arman\Documents\vsCode\test\req/raygui.h:213:44: note: in definition of macro 'RAYGUI_CALLOC'   
  213 |     #define RAYGUI_CALLOC(n,sz)     calloc(n,sz)
      |                                            ^
In file included from C:\Users\arman\Documents\vsCode\test\main.cpp:5:
C:\Users\arman\Documents\vsCode\test\req/raygui.h:3518:42: error: 'Font' {aka 'struct Font'} has no member named 'glyphCount'
 3518 |                 for (int i = 0; i < font.glyphCount; i++) fread(&font.recs[i], 1, sizeof(Rectangle), rgsFile);
      |                                          ^~~~~~~~~~
C:\Users\arman\Documents\vsCode\test\req/raygui.h:3521:22: error: 'Font' {aka 'struct Font'} has no member named 'glyphs'
 3521 |                 font.glyphs = (GlyphInfo *)RAYGUI_CALLOC(font.glyphCount, sizeof(GlyphInfo));    
      |                      ^~~~~~
C:\Users\arman\Documents\vsCode\test\req/raygui.h:3521:32: error: 'GlyphInfo' was not declared in this scope
 3521 |                 font.glyphs = (GlyphInfo *)RAYGUI_CALLOC(font.glyphCount, sizeof(GlyphInfo));    
      |                                ^~~~~~~~~
C:\Users\arman\Documents\vsCode\test\req/raygui.h:3521:43: error: expected primary-expression before ')' 
token
 3521 |                 font.glyphs = (GlyphInfo *)RAYGUI_CALLOC(font.glyphCount, sizeof(GlyphInfo));    
      |                                           ^
C:\Users\arman\Documents\vsCode\test\req/raygui.h:3522:42: error: 'Font' {aka 'struct Font'} has no member named 'glyphCount'
 3522 |                 for (int i = 0; i < font.glyphCount; i++)
      |                                          ^~~~~~~~~~
C:\Users\arman\Documents\vsCode\test\req/raygui.h:3524:33: error: 'Font' {aka 'struct Font'} has no member named 'glyphs'
 3524 |                     fread(&font.glyphs[i].value, 1, sizeof(int), rgsFile);
      |                                 ^~~~~~
C:\Users\arman\Documents\vsCode\test\req/raygui.h:3525:33: error: 'Font' {aka 'struct Font'} has no member named 'glyphs'
 3525 |                     fread(&font.glyphs[i].offsetX, 1, sizeof(int), rgsFile);
      |                                 ^~~~~~
C:\Users\arman\Documents\vsCode\test\req/raygui.h:3526:33: error: 'Font' {aka 'struct Font'} has no member named 'glyphs'
 3526 |                     fread(&font.glyphs[i].offsetY, 1, sizeof(int), rgsFile);
      |                                 ^~~~~~
C:\Users\arman\Documents\vsCode\test\req/raygui.h:3527:33: error: 'Font' {aka 'struct Font'} has no member named 'glyphs'
 3527 |                     fread(&font.glyphs[i].advanceX, 1, sizeof(int), rgsFile);`

**Comment by raysan5** [comment]
@ejamshidiasl I'm afraid it should be used with latest raylib from github master branch.

**Comment by ejamshidiasl** [comment]
i installed raylib from vcpkg (3.7.0#1)

**Comment by raysan5** [comment]
@ejamshidiasl I'm afraid that's not latest version from github master branch, it should be 4.0

**Comment by nbdy** [comment]
Yeah, I misunderstood and revoke my first statement. Sorry.
