### ISSUE TITLE
[feature]can change raygui to c++

### ISSUE THREAD

**Issue by annopnod** [raysan5/raygui#175]
i test  use raygui  hard programming for me

or add new repository raygui to rayguipp

**c code**
bool GuiTextBox(Rectangle bounds, char* text, int textSize, bool editMode)

**c++ code**
//update
GuiTextBox guitext=GuiTextBox(Rectangle bounds); 
guitext.disable=true; // bool editMode
guitext.text="test";//  char* text to string
guitext.maxlength=1234//int textSize
guitext.backgroundcolor=RED//raylib color
guitext.textcolor=RED//raylib color
guitext.focus(); 

//render
guitext.render()//drawing GuiTextBox

**Comment by raysan5** [comment]
Sorry, no plans to change to C++.
