### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by chrisws** [raysan5/raygui#181]
GuiTextBox() may attempt so overwrite the contents of the `char *text` argument, so passing in the string constant "*****" doesn't work. This may just be my build settings, but gcc doesn't seem to allow `-fpermissive` to be disabled. 

https://github.com/raysan5/raygui/blob/4f933c1e81c7af94716b7b420fc90db9de739839/src/raygui.h#L3149

```
./raygui/src/raygui.h:3150:55: error: invalid conversion from ‘const char*’ to ‘char*’ [-fpermissive]
 3150 |             ((*secretViewActive == 1) || textEditMode)? text : "****************", textMaxSize, textEditMode)) textEditMode = !textEditMode;
      |             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                       |
      |                                                       const char*
```

**Comment by Peter0x44** [comment]
> gcc doesn't seem to allow -fpermissive to be disabled.
Passing -fpermissive removes the error for me. I think you have things the wrong way around, the error is not being generated by passing -fpermissive, it is on by default. Passing -fpermissive seems to make gcc "more permissive"

> GuiTextBox() may attempt so overwrite the contents of the char *text argument, so passing in the string constant "*****" doesn't work.
As explained in the comment, it is the different types of the string literals in C or C++
in both, writing to a string literal is UB and shouldn't happen. The function later passes this pointer to GuiTextBox with editMode false, so I don't believe the function writes to the string.

**Comment by chrisws** [comment]
Thanks Peter0x44 - I thought I had tried adding `-fpermissive`, but you are correct and my build now completes successfully.
