### ISSUE TITLE
Double definition of RAYGUI_ICON_FILE_NEW

### ISSUE THREAD

**Issue by ffreling** [raysan5/raygui#191]
In the `guiIconName` enum, there is 2 definitions for `RAYGUI_ICON_FILE_NEW`.

- https://github.com/raysan5/raygui/blob/4466262b50dd71b9d2618ca89749e18cd0802e8a/src/raygui.h#L571
- https://github.com/raysan5/raygui/blob/4466262b50dd71b9d2618ca89749e18cd0802e8a/src/raygui.h#L766

I tried compiling with zig and it treats this redefinition as an error.

I think this error originates from https://github.com/raysan5/raygui/commit/6d79cdf2fd1493122c662084e29036beda7e956b

**Comment by raysan5** [comment]
@ffreling Thanks for reporting! Reviewed!
