### ISSUE TITLE
#define RAYGUI_CUSTOM_ICONS or #define RAYGUI_NO_ICONS causes errors

### ISSUE THREAD

**Issue by GamerZ0216** [raysan5/raygui#199]
This is something that I was testing. Trying to make new icons with rGuiIcons and it stats that we need to
`#define RAYGUI_CUSTOM_ICONS`
in order to get custom icons working in our GUI application. But after doing it causes an error like
`guiIconScale was not defined in this scope`. This is because in raygui.h, the line
863 `static unsigned int guiIconScale = 1;           // Icon default scale `
is under the line
850 `#if !defined(RAYGUI_NO_ICONS) && !defined(RAYGUI_CUSTOM_ICONS)`
. This causes the `guiIconScale` to not be declared when we
`#define RAYGUI_CUSTOM_ICONS`
. To fix it, Move the line
863 `static unsigned int guiIconScale = 1;           // Icon default scale `
above the line
850 `#if !defined(RAYGUI_NO_ICONS) && !defined(RAYGUI_CUSTOM_ICONS)`
. Doing that causes the error to be fixed and maybe everything would work just fine. It did worked for me when I edited the code to include that fix.

**Comment by raysan5** [comment]
Issue reviewed!
