### ISSUE TITLE
example Makefile misconfigured

### ISSUE THREAD

**Issue by Hasdan** [raysan5/raygui#209]
Hello,

I just git clone this repository and wanted to compile the examples. However, upon using make, I was faced with these error messages:

```
make: *** No rule to make target 'image_raw_importer/image_raw_importer', needed by 'all'.  Stop.
make: *** No rule to make target 'scroll_panel/gui_scroll_panel', needed by 'all'.  Stop.
make: *** No rule to make target 'text_box_selection/textbox_extended_demo', needed by 'all'.  Stop.
```

I each time solved these by changing the names to those of the associated directories and files inside the Makefile, but I am unsure whether this is normal behaviour or not.

**Comment by raysan5** [comment]
@Hasdan This Makefile is not updated, feel free to chnage it and send a PR.

**Comment by Hasdan** [comment]
Hello,

I sort of forgot to check here since yesterday. ^^'
However, some examples are no longer compatible with the last version of raylib, for example
```
controls_test_suite/controls_test_suite.c: In function ‘main’:
controls_test_suite/controls_test_suite.c:132:35: warning: implicit declaration of function ‘LoadDroppedFiles’; did you mean ‘ClearDroppedFiles’? [-Wimplicit-function-declaration]
  132 |             char **droppedFiles = LoadDroppedFiles(&dropFileCount);
      |                                   ^~~~~~~~~~~~~~~~
      |                                   ClearDroppedFiles
```

I may change them this week if I find time, but I'm not sure I will.

**Comment by raysan5** [comment]
raylib was changed yesterday with examples, they are ACTUALLY compatible with latest version of raylib from github master branch.
