### ISSUE TITLE
Bad intersection detection when a "pixel perfect" rendering is in use

### ISSUE THREAD

**Issue by DeexCoding** [raysan5/raygui#214]
You probably know what I mean by pixel perfect rendering. You render to a texture and then you upscale it and render it to the backbuffer. The problem is when I start doing my gui stuff, the mouse detection gets messed up, because it uses the window bounds instead of the render texture's bounds.
### I suggest adding:
- BeginVirtualCheckBounds(int virtualWidth, int virtualHeight) : It's basically called when you do BeginTextureMode(renderToUpscale), and this lets the library know that it should map the mouse coordinates to these bounds.
- EndVirtualCheckBounds() : Lets the library know that you no longer wish to detect input from these bounds

**Comment by raysan5** [comment]
@DeexCoding this is out of scope for raygui but you can manage it with raylib. Actually you have an usage example on [`rFXGen` code](https://github.com/raysan5/rfxgen/blob/master/src/rfxgen.c#L516).
