### ISSUE TITLE
Icons don't scale with the text that they're drawn with

### ISSUE THREAD

**Issue by ksdhans** [raysan5/raygui#215]
When the text size is changed, the icons that are drawn remain at their original size. I expected them to scale proportionally along with the font. 

For example:
GuiSetStyle(DEFAULT, TEXT_SIZE, 40);
GuiButton((Rectangle){ 25, 25, 280, 70 }, GuiIconText(RICON_EXIT, "Quit"));

Will draw a button with nicely sized text, but a tiny exit icon. I see no way to change this behaviour, other than to manually draw the icons yourself...

**Comment by raysan5** [comment]
@ksdhans You can use `GuiSetIconScale()` to define icons scale (x2, x3, x4...).

**Comment by ksdhans** [comment]
GuiSetIconScale() isn't defined in the 4.0.0 branch (of Raylib, not the raygui repo). Is this a new function?
