### ISSUE TITLE
Color selection bar won't move until the big color gradient has been clicked at least once

### ISSUE THREAD

**Issue by mandar1jn** [raysan5/raygui#216]
So, I have a variable called portalColor. I have a color selector that takes the portalColor as the argument, and the resulting color is assigned back to portalColor. When I start the program and immediately use the slider instead of the gradient, the slider won't move. You are required to touch the gradient first

**Comment by raysan5** [comment]
@mandar1jn Sorry, I can't understand the issue. I just tested `GuiColorPicker` in `controls_test_suite` and it works as expected.

Please, could you provide a minimal code sample illustrating the issue?

**Comment by mandar1jn** [comment]
```cpp
#include <stdio.h>
#include <wchar.h>

#include "raylib.h"

#define RAYGUI_IMPLEMENTATION
#include "raygui.h"

Color portalColor = RAYWHITE;

void DrawPortalControls();

int main()
{
	InitWindow(800, 600, "Skylanders Editor");
	SetTargetFPS(120);
	while (!WindowShouldClose())
	{
		BeginDrawing();

		ClearBackground(RAYWHITE);

		GuiDrawRectangle({ 0, 0, (float)GetScreenWidth(), 30 }, 1, BLACK, RAYWHITE);

		DrawPortalControls();

		EndDrawing();
	}

	CloseWindow();
}

void DrawPortalControls()
{



	portalColor = GuiColorPicker({ (float)GetScreenWidth() - 130, 35, 100, 100}, "Select portal color", portalColor);
}
```
