### ISSUE TITLE
How to create a project easily?

### ISSUE THREAD

**Issue by AyushKoul00** [raysan5/raygui#218]
I am new to building projects so I don't know understand how to build this. I saw that you have a repo for raylib where you setup the project using premake and that worked. Is there one like that for raygui? If not, could you explain step by step how to set it up using VS2022?

**Comment by raysan5** [comment]
This repo already includes several setup projects as reference.

**Comment by AyushKoul00** [comment]
The repo only has info regarding how to run it using cmd using GCC in different OS. I don't see anywhere how to integrate this into a VS project. As I mentioned before, raylib had a separate repo that used premake to set this up and that was working for me. Is there anything similar for raygui?

**Comment by raysan5** [comment]
@raysan5 premake system for raylib was created by a user, raygui has nothing similar afaik. raygui contains several examples for reference and the VS2022 projects already preconfigured for those examples. That material should be more than enough to get started.

**Comment by AyushKoul00** [comment]
Where are the vs2022 projects? Do you mean in the projects/ directory? As for the examples, i dont have a problem understand the code. Most examples use the raylib header file and the raygui header file but the issue is when I try to build. I am unable to find references to do this in VS. Like I mentioned before, the examples are tailored towards cmake or building from cmd

**Comment by raysan5** [comment]
@AyushKoul00 Just tried the provided `projects/VS2022` solution and it works perfectly for me. Make sure you are using latest raylib from GitHub when linking.

I recommend that you join raylib Discord and ask there, there are specific channels for raygui and environment configuration, and many users ready to help.
