### ISSUE TITLE
Throws Errors in Visual Studio

### ISSUE THREAD

**Issue by be-thomas** [raysan5/raygui#222]
This code throws a lot of errors in Visual Studio, I went ahead and made the changes.

I just used #if defined(_WIN32) to check if it is windows, so these new codes only affect windows platforms

I have already created  a pull request #221

**Comment by raysan5** [comment]
@be-thomas I'm afraid you change the coding style and spacing in the PR, no plans to change that.

About MSVC, I use raygui daily with MSVC for my tools development and I have no problem with it.

**Comment by be-thomas** [comment]
doesn't it gives errors like to use sscanf_s instead of sscanf,
fopen_s instead of fopen,
sprint_s instead of sprintf
?

**Comment by raysan5** [comment]
@be-thomas those function variants (`*_s()`) of the standard C library versions have been created by Microsoft and they are not standard. To avoid those errors/warning you should define:
```c
#define _CRT_SECURE_NO_WARNINGS
```
