### ISSUE TITLE
Is there a way to set different font size of text?

### ISSUE THREAD

**Issue by atakhan** [raysan5/raygui#225]
Hi, is there a way to set different font size of text?
PS thank you for this awesome library!

**Comment by atakhan** [comment]
Yes! i found it! )
here is how to do it
`GuiSetStyle(DEFAULT, TEXT_SIZE, 40);`

**Comment by raysan5** [comment]
@atakhan Hi! Glad you like raygui! 😄

Good to know youalready found how to change text size!

Hope you enjoy it!
