### ISSUE TITLE
Using raygui elements with `BeginMode2D`

### ISSUE THREAD

**Issue by furudbat** [raysan5/raygui#226]
Hi,
I want to "zoom" on  my raygui elements and uses `BeginMode2D`, and it works for the rendering part, but the Mouse collision doesn't work any more.
_Found this examples: [core_smooth_pixelperfect](https://www.raylib.com/examples/core/loader.html?name=core_smooth_pixelperfect) and [core_window_letterbox](https://www.raylib.com/examples/core/loader.html?name=core_window_letterbox)_

My "WorldScreen" (for Scene Rendering) is 320x240, but my window size is 640x480, so I use a zoom-factor of `2.0`.

```cpp
// init some elements and stuff
inline static constexpr auto SceneWidth = 320;
inline static constexpr auto SceneHeight = 240;
inline static constexpr Rectangle layoutRecs[23] = {
      {0, 0, SceneWidth, SceneHeight},

      {anchor01.x, anchor01.y + row.y*0, 70, 30},
      {anchor01.x + 75, anchor01.y + row.y*0 + 2, SceneWidth - 169 - 8, 25},
      {SceneWidth - anchor01.x - 88, anchor01.y + row.y*0 + 2, 85, 25},
      ...
};

inline static constexpr auto ScreenWidth = 640;

// rendering
constexpr auto SceneZoom = static_cast<float>(ScreenWidth) / static_cast<float>(SceneWidth);
constexpr Camera2D SceneCamera = {
                .offset = { 0, 0 },         // Camera offset (displacement from target)
                .target = { 0, 0 },         // Camera target (rotation and zoom origin)
                .rotation = 0.0F,           // Camera rotation in degrees
                .zoom = SceneZoom,
 };

BeginMode2D(SceneCamera);
    // render Scene
    GuiWindowBox(layoutRecs[0], ...);
    GuiButton(layoutRecs[2], ...);
    ...
EndMode2D();
```

Some sort of `GetVirtualMousePosition` and `CheckCollisionPointRecWithCamera2D` (used by raygui) would be nice or a "virtual Gui camera" (for collision checks):
```
          BeginMode2D(SceneCamera);
            GuiBeginVirtualMouse(SceneCamera);
            // render scene
            GuiEndVirtualMouse();
          EndMode2D();
```

---
OS: Linux
raylib version: 4.2.0
raygui version: 3.2
uses C++20 for my Project

**Comment by raysan5** [comment]
@furudbat raylib provides two functions to deal with that:
```c
RLAPI void SetMouseOffset(int offsetX, int offsetY);          // Set mouse offset
RLAPI void SetMouseScale(float scaleX, float scaleY);         // Set mouse scaling
```
It's up to the user to manage it properly.
