### ISSUE TITLE
Control button state from code?

### ISSUE THREAD

**Issue by Ramito** [raysan5/raygui#227]
Hello!

Can I set a buttons hover state from code? I would like to control my buttons with a gamepad and/or mouse and display the same hover state for the "selected button".

Is there a practical way to achieve this?

(Sorry if this is not the place to ask questions, as this really isn't an issue);

**Comment by raysan5** [comment]
@Ramito You can use `GuiSetState(STATE_FOCUSED);` to force a specific state style.

**Comment by Ramito** [comment]
Gracias!
