### ISSUE TITLE
MaximizeWindow() doesn't resize

### ISSUE THREAD

**Issue by nvrrdt** [raysan5/raygui#230]
I'm on Linux Mint.
I issue 'make PLATFORM=PLATFORM_DESKTOP'.

I do:
`InitWindow(600, 400, "bla");
MaximizeWindow();`

My Makefile is:
`CC = gcc
CFLAGS = -c -g -Wall -I../include
LDFLAGS = 
LIBS = -lm -lraylib

SOURCEDIR = .
BUILDDIR = ../build

EXECUTABLE = bon
SOURCES = $(wildcard $(SOURCEDIR)/*.c)
OBJECTS = $(patsubst $(SOURCEDIR)/%.c,$(BUILDDIR)/%.o,$(SOURCES))

all: dir $(BUILDDIR)/$(EXECUTABLE)

dir:
	mkdir -p $(BUILDDIR)

$(BUILDDIR)/$(EXECUTABLE): $(OBJECTS)
	$(CC) $(LDFLAGS) $(OBJECTS) $(LIBS) -o $@

$(OBJECTS): $(BUILDDIR)/%.o : $(SOURCEDIR)/%.c
	$(CC) $(CFLAGS) $< -o $@

clean:
	rm -f $(BUILDDIR)/*.o $(BUILDDIR)/$(EXECUTABLE)

.PHONY : clean`

I found in the raylib code that MaximizeWindow() involves glfw3, so I added glfw3 to the flags in the Makefile, but also that didn't succeed to maximize the window.
I also tried to GetMonitorWidth and GetMonitorHeight in InitWindow, but then then the window is overlapped by the taskbar.

One of the first lines in the output also reads: WARNING: GLFW: Failed to find selected monitor

**Comment by raysan5** [comment]
I think window must be resizable to be maximizable.

Thy setting window as resizable before trying to maximize it.
