### ISSUE TITLE
Errors in the raygui.h file

### ISSUE THREAD

**Issue by Bjorn-is-my-name** [raysan5/raygui#233]
I dont know if this is a problem on my end but i will post it anyways because im not sure.

I'm already working with raylib.h so i just put raygui.h in my include folder, added the define to my program and tried to build the exe.

i got some errors and had a look, but they are very simple:

Line 1571 -> if (GuiButton((Rectangle){tabBounds.x + tabBounds.width - 14 - 5, tabBounds.y + 5, 14, 14}, GuiIconText(ICON_CROSS_SMALL, NULL)))

Line 1578 -> GuiDrawRectangle((Rectangle){bounds.x, bounds.y + bounds.height - 1, bounds.width, 1}, 0, BLANK, GetColor(GuiGetStyle(TOGGLE, BORDER_COLOR_NORMAL)));

Line 4243 -> DrawTextCodepoint(guiFont, codepoint, (Vector2){position.x + textOffsetX, position.y + textOffsetY}, (float)GuiGetStyle(DEFAULT, TEXT_SIZE), tint);

Error: expected an expression

I had to remove the brackets around Rectanlge and Vector2

Line 4142 -> char **lines = GetTextLines(text, &lineCount);

Line 4151 -> lines[i] = GetTextIcon(lines[i], &iconId); // Check text for icon and move cursor

Error: argument of type "const char *" is incompatible with parameter of type "char *"

I had to cast both text and the output of GetTextIcon to "char *"

**Comment by raysan5** [comment]
The compound literals issue is a C99 feature, not available in C++, the `const` issues should be just warnings.
