### ISSUE TITLE
Push/Pop style variables

### ISSUE THREAD

**Issue by muit** [raysan5/raygui#234]
I have not seen if there is a way to push/pop style variables.

Therefore I would like to propose for this to be added since it makes code much simpler when you want to make sure the previous state is kept once you finish what you are doing.

For example:
```cpp
auto lastStyle = GuiGetStyle(LABEL, TEXT_ALIGNMENT);
GuiSetStyle(LABEL, TEXT_ALIGNMENT, TEXT_ALIGN_CENTER);
GuiLabel(...);
GuiSetStyle(LABEL, TEXT_ALIGNMENT, lastStyle);
```
would become
```cpp
GuiPushStyle(LABEL, TEXT_ALIGNMENT, TEXT_ALIGN_CENTER);
GuiLabel(...);
GuiPopStyle(LABEL, TEXT_ALIGNMENT);
```

**Comment by muit** [comment]
As a side topic, some feedback too:
As an user, it is hard to know what is and what is not an style variable. Its also hard to remember the relation between a label type and its value.

E.g: TEXT_ALIGNMENT doesn't necessarily transmit to the user that TEXT_ALIGN_CENTER is a value of it and is hard to find on its own.

Even though raygui and imgui are for different purposes, I think it might be interesting to check how imgui solves this topics

**Comment by raysan5** [comment]
@muit Yeah, it was considered but unfortunately I tried to keep `raygui` as much immediate-mode as possible, avoiding any kind of user-data storage. Actually, I even removed frameCounters required for i.e. text caret blinking to avoid to store transient data.

A push/pop system requires some internal storage mechanism...

**Comment by raysan5** [comment]
@muit Afaik, imgui keeps a user context and stores there all required data. I designed `raygui` with a pure immediate-mode approach (as far as possible).

**Comment by muit** [comment]
How does this change the immediateness of it? In the sense that there is a need to store some data? 

I think the benefits in the user syntax would be so big it should easily be worth it

**Comment by muit** [comment]
I guess the question would be if it being purely immediate is worth it considering a library serves a purpose. in this case to be used to create interfaces.

If creating interfaces is verbose, users wont like it.

**Comment by raysan5** [comment]
> How does this change the immediateness of it? In the sense that there is a need to store some data?

What do you refer to? A push/pop mechanism requires a stack to store data.

 > I think the benefits in the user syntax would be so big it should easily be worth it

Completely agree but that's a design decision I took when I created this project and I like to follow it. If I design another imgui library in the future I will probably follow a completely different approach.

 > If creating interfaces is verbose, users wont like it.

`raygui` server perfectly my pourpose of [creating small tools](https://raylibtech.itch.io/), I use it daily and sincerely, I really like it. I probably get get used to it and embraced its limitations.

**Comment by muit** [comment]
I like it too, I only debate this because I do :)

Yes, I refer to stacks as "store some data".

I understand it serves your purpose, and it being your library its also your choices. I'm just talking about a topic I usually focus on my professional career. That involves writing APIs that other people apart from just me are happy to use.

So then the question changes. Is this a library intended for our personal use? or would you like more people to use it too? as a goal of the library I mean. If it was me, the answer to this would guide the answer to the issue itself

**Comment by raysan5** [comment]
raygui was originally created for my needs exclusively, actually I think not many people is using it a part of me (and that's perfectly fine) but like other libraries I have (raylib, rpng, rres...) I took some initial design decisions and I stay true to them.

One reason to make it open source, like raylib, is to allow other people to pick it up, fork it and customize it for their needs.

I'm not working on a company, raygui is another hobby project, so, I think many of the corporate considerations when delivering a UI library for a team do not apply here, starting with the coding language selected.
