### ISSUE TITLE
Scroll behavior

### ISSUE THREAD

**Issue by n67094** [raysan5/raygui#239]
Hi,

If you press the scrollbar and drag/slide the mouse outside the scrollbar bounds it didn't scroll anymore (it's a little frustrating :sweat_smile:), if I'm right is probably somewhere by there:

https://github.com/raysan5/raygui/blob/d4b9d1fb32f1536f651ef4bfb69c9012001bfb9d/src/raygui.h#L1589

**Comment by raysan5** [comment]
@n67094 I'm afraid it's not easy to find a solution for this problem considering raygui is an immediate-mode gui and it does not store information between frames.

**Comment by n67094** [comment]
You better know for sure 😅 but is guiState not THE state ? 🤔 (note that I didn't read the whole code, but I should sorry)

**Comment by raysan5** [comment]
@n67094 Not really, `guiState` is a global variable used to force the state of controls externally, for example, to disable them or force a focused state. Once set, it applies to all controls.

**Comment by n67094** [comment]
Ah ok i see 🤔 Maybe Nuklear can be investigated to see how they handle it (I can't confirme they don't have a global state, but I can confirme that their scrollbar work as "asked" if I can say)

Thank you for your time 😁

**Comment by raysan5** [comment]
@n67094 Afaik Nuklear use a global context but feel free to investigate it! 👍😄

**Comment by raysan5** [comment]
Investigated Nuklear, it keeps a context state to store required information, also implementation is way more complex than raygui one: https://github.com/Immediate-Mode-UI/Nuklear/blob/master/src/nuklear_scrollbar.c

raygui uses a different approach and unfortunately it has to deal with its limitations/constraints.

**Comment by n67094** [comment]
Ok I see, thanks 🙂
