### ISSUE TITLE
Fix `Texture2D` with `RAYGUI_STANDALONE`

### ISSUE THREAD

**Issue by leiradel** [raysan5/raygui#244]
`Texture2D` is coupled with OpenGL, using an `unsigned int` to hold the actual texture. I want to make raygui work with a SDL2 backend, which needs a pointer to hold the texture.

I see that `Texture2D` is defined in `raylib.h`, but when `RAYGUI_STANDALONE` is defined the intent is *not* to use raylib at all, so I wonder if it's ok to modify `id` in that structure to be a `void*`.

Once my changes are finished and tested, I'll send a PR back to raygui.

**Comment by raysan5** [comment]
@leiradel I'm afraid at this moment raygui is quite coupled to raylib, `Texture2D` and `Font` are examples of that coupling. It needs a review but I think using a `void *` is not the best solution, actually an OpenGL texture is defined by and identifier...

In any case, we can check how to approach it once you got it working on your fork.

By the way, this was an open discussion on raylib Discord raygui channel recently.

**Comment by leiradel** [comment]
Yeah I see that it's very coupled. I'm trying anyway, since I'd like to get raygui working in my app.

> but I think using a void * is not the best solution

My first choice was a `uintptr_t` but I wasn't sure if I could include `stdint.h` in raygui. Is that a better option?

**Comment by leiradel** [comment]
Never mind, the effort is already too great and I still can't make a simple GUI render in my app. It's a shame because it looks really simple to use and great to look at.
