### ISSUE TITLE
undefined reference to `GetCodepointNext'

### ISSUE THREAD

**Issue by datascribbler777** [raysan5/raygui#245]
Trying to build portable_window.c
Using Raylib 4.2.0

-Wall gives:
warning: implicit declaration of function 'GetCodepointNext'; did you mean 'GetCodepoint'? [-Wimplicit-function-declaration]
 2154 |             GetCodepointNext(text, &codepointSize);
      |             ^~~~~~~~~~~~~~~~
      |             GetCodepoint

Then undefined errors appear.
Also get undefined errors for timeEndPeriod and timeBeginPeriod

Maybe I am doing something wrong?

**Comment by raysan5** [comment]
@datascribbler777 raygui 3.5-dev requires raylib 4.5-dev

**Comment by weskerfoot** [comment]
I'm confused by the versions. Where is raylib 4.5-dev ? I don't see it listed anywhere here https://github.com/raysan5/raylib/releases

**Comment by raysan5** [comment]
@weskerfoot `raylib 4.5-dev` refers to the latest development version and is always the master branch of GitHub. It is ususally stable. Official `raylib 4.5` is going to be released soon, hopefully this month.
