### ISSUE TITLE
Dear ImGui's `io.WantCaptureMouse` and `io.io.WantCaptureKeyboard` equivalents

### ISSUE THREAD

**Issue by KyrietS** [raysan5/raygui#246]
Hi,

Are there Dear ImGui's equivalents for `io.WantCaptureMouse` and `io.WantCaptureKeyboard` flags?

Is there any API in raygui for checking whether an input should be "consumed/handled" by UI and not propagated further? Any plans for adding it?

Thanks 😀

**Comment by raysan5** [comment]
raygui provides `GuiLock()` and `GuiUnlock()` to avoid inputs being consumed by the UI elements but it's up to the user to manage what happens with those inputs after that.

No plans to add any specific functionality beyond that...
