### ISSUE TITLE
Setup CPack-based packaging for `raygui`

### ISSUE THREAD

**Issue by KOLANICH** [raysan5/raygui#251]

**Comment by raysan5** [comment]
I'm not a fun of CMake, no plans to support CPack

**Comment by KOLANICH** [comment]
>no plans to support CPack
>closed this as completed

Shouldn't it be `closed this as not planned` then?

**Comment by KOLANICH** [comment]
>not a fan of CMake

Noone is a fan of CMake, but it is currently the best build system available with own killer features.
