### ISSUE TITLE
How to fix textboxes

### ISSUE THREAD

**Issue by ElectroGamesYT** [raysan5/raygui#253]
Hello, I noticed the textboxes are horrible, ex. can't use arrow keys, can't highlight the text, etc.
Is it possible to make the textboxes more normal compared to how textboxes usually are?
Also is it possible to give the textboxes hints? So when there is nothing typed in the box, it will show a "hint" text.the when the user clicks on the textbox, the hint goes away.
Thanks.

**Comment by raysan5** [comment]
@ElectroGamesYT raygui is a simple immediate-mode ui library, it implies some limitations. If you are looking for full-featured ui components probably raygui won't fit your needs. Implementing the features you mention would imply a number of state variables that due to the nature of the library can not be saved.

**Comment by ElectroGamesYT** [comment]
Hmm okay. Do you know if there are any alternatives?
Also I tried creating another class but when I include my main class, or the raygui, I get a bunch of errors for all of the controls saying they already exist and some other errors, here are a few of the errors:
```
LNK1169	one or more multiply defined symbols found
LNK2005	main already defined in Editor.obj
LNK2005	GuiWindowBox already defined in Editor.obj	
LNK2005	GuiValueBox already defined in Editor.obj
LNK2005	GuiUnlock already defined in Editor.obj
LNK2005	GuiToggleGroup already defined in Editor.obj
```

**Comment by raysan5** [comment]
About the duplicate symbols issue, that's because `RAYGUI_IMPLEMENTATION` must be defined in only one compilation unit.

About alternatives, I recommend using [`Dear ImGui`](https://github.com/ocornut/imgui).
