### ISSUE TITLE
Add instructions to build raygui.dll with cl.exe?

### ISSUE THREAD

**Issue by erg** [raysan5/raygui#254]
I don't have mingw installed so I got a raygui.dll from this command-line:

```
# copy src\raylib.h src\raylib.c
 cl /O2 /I ../raylib/src/ /D_USRDLL /D_WINDLL /DRAYGUI_IMPLEMENTATION /DBUILD_LIBTYPE_SHARED src/raygui.c /LD /Feraygui.dll /link /LIBPATH ../raylib/build/raylib/Release/raylib.lib /subsystem:windows /machine:x64
```

Some of it might be unnecessary, but please consider trying to golf it and then adding this to the main readme next to the mingw command. At least it will be in the issue tracker now if someone else needs to build it.

**Comment by raysan5** [comment]
@erg Added to README!
