### ISSUE TITLE
circular dependency

### ISSUE THREAD

**Issue by MrKleeblatt** [raysan5/raygui#259]
In your function `GuiSetStyle` there is a call to ` GuiLoadStyleDefault();` but if you load the first style for the first time this function will also call `GuiSetStyle` again and you and up in an infinite loop.
Maybe it's just because I messed with your code structure (can you please make more than just one file, this just looks terrible, but the code is so nice).
But maybe you can reproduce it by yourself.

By commenting `if (!guiStyleLoaded) GuiLoadStyleDefault();` out everything seems to work now.

Good night :)

**Comment by raysan5** [comment]
@MrKleeblatt I'm afraid I can't see the issue you mention. 

1. If you call `GuiLoadStyleDefault()` before any `GuiSetStyle()` call, first line just sets `guiStyleLoaded = true;` so any subsequent call to `GuiSetStyle()` avoids calling `GuiLoadStyleDefault()` again.

2. If you don't call `GuiLoadStyleDefault()` or call `GuiSetStyle()`, default style is set automatically **if not previously set**.

**Comment by MrKleeblatt** [comment]
Nevermind, my head was somewhere else.
