### ISSUE TITLE
GetButton() help needed

### ISSUE THREAD

**Issue by valito1234** [raysan5/raygui#261]
I'm writing a code using raygui for buttons and I get 2 errors when debugging.
LNK1120 and LNK2019.
What do I need to do to remove them?

**Comment by raysan5** [comment]
@valito1234 I'm afraid I have no idea what `LNK1120` and `LNK2019` mean.

Please, provide more info or the compilation output log.

**Comment by valito1234** [comment]
![error](https://user-images.githubusercontent.com/127986435/225715019-82e30f3a-1e2c-476b-9d39-d315253e6be3.png)
This is what I see everytime I try to debug.

**Comment by RobLoach** [comment]
raygui is a single-header library that shouldn't really need any linking. Did you link raylib incorrectly?

**Comment by raysan5** [comment]
It looks like an usage problem, not an issue with the library. Please, join raylib Discord for usage help.
