### ISSUE TITLE
Next release?

### ISSUE THREAD

**Issue by shelvick** [raysan5/raygui#262]
I'm an author of a language binding + game toolkit that incorporates both Raylib and Raygui. The README says that the master branches remain aligned, so I was wondering if that also applies to tagged releases. Since you just released Raylib 4.5, will there be a Raygui release as well?

**Comment by raysan5** [comment]
@shelvick Yeah, I plan to release `raygui 3.5` soon but I'm working in too many things and I don't know when that _soon_ will be...

I'd like to review for `raygui 3.5` the `GuiSlider*()`, `GuiScrollBar()` and `GuiTextBox()`.
