### ISSUE TITLE
Automatic layout?

### ISSUE THREAD

**Issue by cesss** [raysan5/raygui#266]
Don't you provide any automatic layout mechanism, even if it's a rudimentary one a la AntTweakBar? The layout tool you wrote is a nice addition, but I usually find myself wanting to quickly have a dialog box with 4 buttons, 3 toggles, and 5 sliders, just in one column, with automatic layout, and inside a scrolled window just in case the height is too large for the display. Reading the readme I was pretty convinced to choose raygui, because it had everything I want, and even in C, which is my language. But then, took a look at the example code, and seeing that all controls are created with a hard-coded Rectangle{} is what put me off 😢

**Comment by raysan5** [comment]
Sorry, an automatic layout system would require some global state accessed by every control on drawing. at the moment this is out of scope.
