### ISSUE TITLE
Undefined references when compiling as shared library on Windows using gcc

### ISSUE THREAD

**Issue by dallas-hyde** [raysan5/raygui#267]
I'm attempting to build a shared library on windows using the provided instructions and I'm getting these errors from gcc:

![1](https://user-images.githubusercontent.com/86331880/230396825-c9a65313-8dc6-43cd-970a-97d5fd1fded8.PNG)
![2](https://user-images.githubusercontent.com/86331880/230396840-1de7588c-a8ab-4325-b401-348ccfec8094.PNG)

I'm using the main branches of both raygui and raylib and have copied raylib.h into the raygui src directory
What am I doing wrong?

**Comment by raysan5** [comment]
You are not linking with raylib library, it requires `-lraylib` parameter
