### ISSUE TITLE
Scrollbar Issues

### ISSUE THREAD

**Issue by ZaneL** [raysan5/raygui#294]
Some of the components with scrollbars have a few issues which make them difficult to use:

1.) When you click down on the scrollbar and drag, it works fine until your mouse goes off of the scrollbar - then the scrollbar quits scrolling. This means that you have to consciously watch your mouse pointer to make sure you stay perfectly within that ~20px wide scroll bar

2.) For some reason, you can't click on the top of the scroll bar and drag down. It only starts scrolling when your mouse cursor is halfway down the height of the scroll component.

3.) The scrollbar on the listview is confusing, because it gives the impression that you can drag it, when all you can do is mouse wheel from item to item.

**Comment by raysan5** [comment]
@ZaneL Are you using latest raygui from github master branch? Issues 1.) and 2.) should be addressed.

About issue 3.) you are right, scrollbar can not be scrolled, just clicked with mouse to move to position.

**Comment by raysan5** [comment]
I'm assuming the issue is fixed. Feel free to comment if it's not the case.
