### ISSUE TITLE
GuiScrollPanel

### ISSUE THREAD

**Issue by wwderw** [raysan5/raygui#297]
GuiScrollPanel is complaining about the 5th argument (last rectangle) and only accepting the first 4 arguments.  I tried the example in this repo and it gives the same error.

Raylib and Raygui are latest from master.

**Comment by raysan5** [comment]
@wwderw in what code example are you getting that error?

**Comment by wwderw** [comment]
The scroll_panel one.  It was actually spitting out quite a lot of errors, but I don't know if because of the one that I was after (which was the first listed in the output) was causing the others to throw or if they were independent of that one.  I wasn't using the rest controls in my own code, so I don't know exactly.

**Comment by raysan5** [comment]
@wwderw Just tested it and it works as expected, using latest `raylib 4.6-dev` and `raygui 4.0-dev`. Make sure you are including the right raygui library.
