### ISSUE TITLE
raygui input separate from display

### ISSUE THREAD

**Issue by SolarLune** [raysan5/raygui#31]
Hello! 

So basically, if you use a RenderTexture2D to scale the screen, the controls for raygui remain where they originally were (i.e. rendering the screen x4 larger doesn't make a button's clickable surface 4 times larger). 

This is to be expected, but it still might be a good idea to add a function to raygui to scale the positions for the mouse cursor according to scalable values to allow you to resize the screen / GUI elements while still maintaining ability to interact with the raygui elements.

**Comment by raysan5** [comment]
Hi @SolarLune, actually that's managed on raylib side with `SetMouseScale()` and `SetMouseOffset()`. Here it is an example of how I managed it on [rFXGen](https://github.com/raysan5/rfxgen/blob/master/src/rfxgen.c#L557).

**Comment by SolarLune** [comment]
Perfect, that's an excellent solution! Seems like it's not listed in the cheatsheet, though; maybe that should be added for the next release. Thanks for the heads-up!
