### ISSUE TITLE
TextBox is very limited

### ISSUE THREAD

**Issue by Filipp-Druan** [raysan5/raygui#319]
I played with https://raylibtech.itch.io/rimageshield and see, that TextBox is very limited. I cant move the cursor, redact text in the middle.  It is sad.
Please, can someone modernize this widget, to make it possible to write a simple text editor? I'd love to do it myself, but I don't know C.
I will happy!

**Comment by raysan5** [comment]
@Filipp-Druan Actually the text editor has already been modernized but `rImageShield` has not been updated yet. I plan to update it in the following weeks.
