### ISSUE TITLE
Portable window example error

### ISSUE THREAD

**Issue by Filipp-Druan** [raysan5/raygui#321]
When I run the portable window example and try to drag the window, it start to twitching and flay away from under cursor.
I would by happy to add a gif record, but I can't.

**Comment by Filipp-Druan** [comment]
Manjaro Linux XFCE.

**Comment by raysan5** [comment]
> Manjaro Linux XFCE.

I'm afraid this issue could be related to XFCE desktop environment. There is not much I can do.

**Comment by AnasASK** [comment]
I noticed the same issue in Pop_OS! Gnome. So it it not only related to xfce.

**Comment by Lecrapouille** [comment]
I noticed the same issue with Debian 11, running with XFCE. I'll check at the code

**Comment by raysan5** [comment]
@Lecrapouille If the problem is on mouse, why does is work as expected on Windows?

**Comment by Lecrapouille** [comment]
@raysan5 I should try on Windows, but I'm noob with Windows. I do not know why on Windows it works, it should not work. When I tried to make my 1st example, I got issue with scrolling the list widget (I forget the name) it was the single widget I add: the scroll was also erratic (while with your example full of widget the scroll worked).

**Comment by jepe-ryhe** [comment]
Hi @raysan5 , I meet the same issue.
After some investigation, I found that when the window position is updated in raylib, the mouse position does not get updated accordingly.
I made this change and it works good on my computer with glfw:
```
static void WindowPosCallback(GLFWwindow* window, int x, int y)
{
    // Set current window position
    CORE.Window.position.x = x;
    CORE.Window.position.y = y;
    double mouseX, mouseY;
    glfwGetCursorPos(window, &mouseX, &mouseY);
    MouseCursorPosCallback(window, mouseX, mouseY);
}
```
Is this the intended behavior? Perhaps we need a mechanism to ensure the mouse position is updated.
