### ISSUE TITLE
raygui unusable for C++ projects

### ISSUE THREAD

**Issue by sduman** [raysan5/raygui#33]
Hi,

I'm attempting to use raygui with my raylib project, but after generating the project files for VS2019 or Make on OSX, a ton of errors are generated when trying to compile the raygui header.

It looks like there's an issue related to both casting and just the general C vs C++ syntax.

(copied from Visual Studio)
`Error	C2065	'RICONS_SIZE': undeclared identifier	raylib-proj	C:\raylib-proj\include\libs\raygui.h	681	
Error	C2065	'RICONS_SIZE': undeclared identifier	raylib-proj	C:\raylib-proj\include\libs\raygui.h	717	
Error	C4576	a parenthesized type followed by an initializer list is a non-standard explicit type conversion syntax	raylib-proj	C:\raylib-proj\include\libs\raygui.h	717	
Error	C3861	'DrawIcon': identifier not found	raylib-proj	C:\raylib-proj\include\libs\raygui.h	717	
Error	C2065	'RICONS_SIZE': undeclared identifier	raylib-proj	C:\raylib-proj\include\libs\raygui.h	721	
Error	C4576	a parenthesized type followed by an initializer list is a non-standard explicit type conversion syntax	raylib-proj	C:\raylib-proj\include\libs\raygui.h	865	
Error	C2065	'RICON_CROSS_SMALL': undeclared identifier	raylib-proj	C:\raylib-proj\include\libs\raygui.h	883	
Error	C2660	'GuiButton': function does not take 1 arguments	raylib-proj	C:\raylib-proj\include\libs\raygui.h	883	
Error	C4576	a parenthesized type followed by an initializer list is a non-standard explicit type conversion syntax	raylib-proj	C:\raylib-proj\include\libs\raygui.h	909	
Error	C4576	a parenthesized type followed by an initializer list is a non-standard explicit type conversion syntax	raylib-proj	C:\raylib-proj\include\libs\raygui.h	979	
Error	C4576	a parenthesized type followed by an initializer list is a non-standard explicit type conversion syntax	raylib-proj	C:\raylib-proj\include\libs\raygui.h	980	
Error	C4576	a parenthesized type followed by an initializer list is a non-standard explicit type conversion syntax	raylib-proj	C:\raylib-proj\include\libs\raygui.h	1156	
Error	C2397	conversion from 'int' to 'float' requires a narrowing conversion	raylib-proj	C:\raylib-proj\include\libs\raygui.h	1156	
Error	C4576	a parenthesized type followed by an initializer list is a non-standard explicit type conversion syntax	raylib-proj	C:\raylib-proj\include\libs\raygui.h	1187	
Error	C4576	a parenthesized type followed by an initializer list is a non-standard explicit type conversion syntax	raylib-proj	C:\raylib-proj\include\libs\raygui.h	1287	
Error	C4576	a parenthesized type followed by an initializer list is a non-standard explicit type conversion syntax	raylib-proj	C:\raylib-proj\include\libs\raygui.h	1440	
Error	C4576	a parenthesized type followed by an initializer list is a non-standard explicit type conversion syntax	raylib-proj	C:\raylib-proj\include\libs\raygui.h	1444	
Error	C4576	a parenthesized type followed by an initializer list is a non-standard explicit type conversion syntax	raylib-proj	C:\raylib-proj\include\libs\raygui.h	1448	
Error	C4576	a parenthesized type followed by an initializer list is a non-standard explicit type conversion syntax	raylib-proj	C:\raylib-proj\include\libs\raygui.h	1453	
Error	C4576	a parenthesized type followed by an initializer list is a non-standard explicit type conversion syntax	raylib-proj	C:\raylib-proj\include\libs\raygui.h	1460	
Error	C4576	a parenthesized type followed by an initializer list is a non-standard explicit type conversion syntax	raylib-proj	C:\raylib-proj\include\libs\raygui.h	1466	
Error	C4576	a parenthesized type followed by an initializer list is a non-standard explicit type conversion syntax	raylib-proj	C:\raylib-proj\include\libs\raygui.h	1481	
Error	C4576	a parenthesized type followed by an initializer list is a non-standard explicit type conversion syntax	raylib-proj	C:\raylib-proj\include\libs\raygui.h	1488	
Error	C4576	a parenthesized type followed by an initializer list is a non-standard explicit type conversion syntax	raylib-proj	C:\raylib-proj\include\libs\raygui.h	1489	
Error	C4576	a parenthesized type followed by an initializer list is a non-standard explicit type conversion syntax	raylib-proj	C:\raylib-proj\include\libs\raygui.h	1490`

**Comment by raysan5** [comment]
It seems related to VS configuration, I'm using raygui to create tools with Visual Studio and it works ok.

**Comment by sduman** [comment]
I've used the out of the box scripts for raylib to generate the project templates. Could you share what configuration you're using for visual studio to bypass the warnings?

This is very easily reproducible by just trying to compile raylib in any version of VS as part of a C++ project.

**Comment by raysan5** [comment]
@sduman Sorry, I closed it too quickly.

**Comment by Skytrias** [comment]
yep sadly unusable in c++ as far as it seems.

getting lots of warnings about { 0 } being used, Types in brackets like (Vector2) or (Rectangle).
also conversions from int to float about 30 errors.
sadly my errors are on german so wont help much to show them

id really like to use raygui!

**Comment by Skytrias** [comment]
also doesnt work with extern "C" { #include "raygui.h" }

**Comment by raysan5** [comment]
Tested with `g++`, lots of warnings but it compiles fine.

Not tested with MSVC just yet.

**Comment by Skytrias** [comment]
was using msvc soory shouldve pointed that out

**Comment by simonwashere** [comment]
Compiling as C using the visual studio tools I am doing this:

#pragma warning( push, 0 )
#pragma warning( disable : 4576 )
#define RAYGUI_IMPLEMENTATION
#define RAYGUI_STANDALONE
#define RAYGUI_STATIC
#include "raygui.h"
#pragma warning( pop )

Agree that it doesn't seem to work compiling as C++ using the visual studio tools.

**Comment by simonwashere** [comment]
With the include done like this:

#pragma warning( push, 0 )
#pragma warning( disable : 4576 )
#define RAYGUI_IMPLEMENTATION
#define RAYGUI_STANDALONE
#define RAYGUI_STATIC
#include "raygui.h"
#pragma warning( pop )

compiling using visual studio command line tools works as C code, for C++ I get these errors:

raygui.h(1193): error C2397: conversion from 'int' to 'float' requires a narrowing conversion
raygui.h(1495): error C2397: conversion from 'int' to 'float' requires a narrowing conversion
raygui.h(1496): error C2397: conversion from 'int' to 'float' requires a narrowing conversion
raygui.h(1497): error C2397: conversion from 'int' to 'float' requires a narrowing conversion
raygui.h(3971): error C2397: conversion from 'float' to 'int' requires a narrowing conversion
raygui.h(3977): error C2397: conversion from 'float' to 'int' requires a narrowing conversion

It doesn't matter to me because I am using C, but putting it here in case it helps.

**Comment by raysan5** [comment]
MSVC conversion errors are just warnings in G++, they can probably be avoided with an explicit cast.

**Comment by SasLuca** [comment]
I did a pull request in which I made raygui.h compatible with C++.
In case anyone wants to use raygui.h with C++ you can look at my fork: 
https://github.com/SasLuca/raygui
https://github.com/raysan5/raygui/pull/44
