### ISSUE TITLE
Flickering window

### ISSUE THREAD

**Issue by sjakk** [raysan5/raygui#331]
**Env: Xorg + GNOME**

https://github.com/raysan5/raygui/assets/87045222/809fb661-affc-4457-aca9-754f0f0c3353

**#321**

**Comment by raysan5** [comment]
It seems this issue is related with https://github.com/raysan5/raygui/issues/321.

The example works as expected on Windows but it seems issue is related to `SetWindowPosition()` function on some Linux distributions.

**Comment by Lecrapouille** [comment]
@sjakk @raysan5 I tried to investigate on ticket 321 since I have the same issue

**Comment by raysan5** [comment]
It seems this issue is related to underlying OS. Not much can be done at raygui level.
