### ISSUE TITLE
error in build raygui with windows + gcc 

### ISSUE THREAD

**Issue by jsbsan** [raysan5/raygui#332]
Hello, when I execute the following line (for building raygui):
copy src/raygui.h src/raygui.c
gcc -o src/raygui.dll src/raygui.c -shared -DRAYGUI_IMPLEMENTATION -DBUILD_LIBTYPE_SHARED -static-libgcc -lopengl32 -lgdi32 -lwinmm -Wl,--out-implib,src/librayguidll.a

I get the following error:
En línea: 1 Carácter: 136
+ ... LIBTYPE_SHARED -static-libgcc -lopengl32 -lgdi32 -lwinmm -Wl,--out-im ...
+                                                                                                              ~
Falta un argumento en la lista de parámetros.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : MissingArgument

It seems that the error is in the way the parameters are set:
-Wl,--out-implib,src/librayguidll.a

could you check it?

Thank you

**Comment by raysan5** [comment]
@jsbsan Just built `raygui.dll` successfully with (MinGW - GCC 12.0.1) using:
```
gcc -o raygui.dll raygui.c -shared -DRAYGUI_IMPLEMENTATION -DBUILD_LIBTYPE_SHARED -static-libgcc -lraylib -lopengl32 -lgdi32 -lwinmm -Wl,--out-implib,libraygui.dll.a
```

**Comment by n-92** [comment]
Does not work for me

![image](https://github.com/raysan5/raygui/assets/8834529/c8b0573b-3aea-4d62-b133-48bd8b1524fb)
