### ISSUE TITLE
make clean on linux not working properly 

### ISSUE THREAD

**Issue by n67094** [raysan5/raygui#334]
I tried to add -delete just like that (c.f below) to get the right result, but others part of the command is complaining, as you can imagine by looking at it ^^.

find -type f -executable -delete | xargs file -i | grep -E 'x-object|x-archive|x-sharedlib|x-executable' | rev | cut -d ':' -f 2- | rev | xargs rm -fv

**Comment by raysan5** [comment]
@n67094 `make clean` is actually trickier than expected, had many issues with it trying to make it multiplatform...

**Comment by anstropleuton** [comment]
But it works properly on raylib's examples...?

**Comment by n67094** [comment]
yes raylib's example only use those 2 commands

```
find . -type f -executable -delete
rm -fv *.o
```

**Comment by raysan5** [comment]
I'm afraid I'm just closing this issue...
