### ISSUE TITLE
`GuiScrollPanel()` improvement

### ISSUE THREAD

**Issue by danielchasehooper** [raysan5/raygui#341]
GuiScrollPanel is kind of annoying to use right now because it requires you to set up the scissor and offset all the controls that should be drawn inside it. The api could be improved if it instead worked like so:

```c
// this draws the panel, sets up the scissor, calls rlPushMatrix and rlTranslatef
GuiBeginScrollPanel(scroll_panel_bounds, "title", content_size); 
    // draw everything you want in the scroll panel
GuiEndScrollPanel(); // restores scissor and pops the matrix
```

**Comment by raysan5** [comment]
I tried to minimize raylib-dependencies and OpenGL functions inside raygui, to make it standalone overwriting some "simple" functions, for that reason clipping is moved to user side. Also raygui does not use the `Begin/End` approach for now but I considered a similar approach for auto-layout placement... for the moment it's on the user-side...
