### ISSUE TITLE
Proposal: Add standard emacs/bash keybindings to GuiTextBox

### ISSUE THREAD

**Issue by VisenDev** [raysan5/raygui#347]
The following [bash/emacs](https://gist.github.com/tuxfight3r/60051ac67c5f0445efee) keybindings would be useful for text input. These bindings seem to be nearly universal across text input implementations. Beyond bash and emacs, I know they are also available in github, and in most webbrowsers

```
<C-a>     goto beginning of line
<C-e>     goto end of line
<C-k>     kill from cursor to end of line
<C-f>      go forward one character
<C-b>     go backward one character
```

**Comment by raysan5** [comment]
I'm afraid this is out of scope for GuiTextBox(). In any case, the most common Home-End would be added.

**Comment by VisenDev** [comment]
> I'm afraid this is out of scope for GuiTextBox(). In any case, the most common Home-End would be added.

I'd like to have this functionality for a simple terminal interface I'm working on using raygui, would you recommend I use a different widget for this functionality, or implement my own custom input box?
