### ISSUE TITLE
I have inkluded raygui.h to the Solution in visual studio 2022.

### ISSUE THREAD

**Issue by NightStalker1000** [raysan5/raygui#351]
I have inkluded raygui.h to the Solution in visual studio 2022.
#include "raylib.h"
#define RAYGUI_IMPLEMENTATION
#include "raygui.h"

I still gets lots of varnings. Se the included fil.
![Fel meddelanden](https://github.com/raysan5/raygui/assets/151570689/0e8b1775-24ea-4a58-8402-efda7d4dc9d1)

**Comment by Manuvalos** [comment]
Here's what I did to fix it, go to project properties -> Configuration Properties -> C/C++ -> Preprocessor -> Preprocessor Definitions, and add the following macros:

_CRT_SECURE_NO_DEPRECATE  
_CRT_NONSTDC_NO_DEPRECATE
