### ISSUE TITLE
Certain theme-fonts are missing characters.

### ISSUE THREAD

**Issue by DannyIsBack1** [raysan5/raygui#354]
The default, jungle and lavanda theme-fonts all display the latin-1 charset characters correclty.
Other theme-fonts like dark do not display these characters.

This works:
![image](https://github.com/raysan5/raygui/assets/80820596/424a6d58-c3ac-4c56-8491-0b973a43d8e6)

This doesnt:
![image](https://github.com/raysan5/raygui/assets/80820596/639c6bac-e8ed-4936-b7f7-b87116adcea2)

**Comment by raysan5** [comment]
@DannyIsBack1 This issue should be fixed with latest commit. Actually, style selector example shows the font available characters for each font!
