### ISSUE TITLE
GuiTextBox bug report

### ISSUE THREAD

**Issue by simonwashere** [raysan5/raygui#36]
Hi,

On line 2710 when you insert a character into the GuiTextBox string you should also add a null terminator:

text[keyCount] = (char)key;
keyCount++;
text[keyCount] = '\0'; (this line is currently missing in the code)

Otherwise it works fine only if the unused parts of the string buffer are zero.

Thanks for writing this great library.

thanks,

Simon

**Comment by raysan5** [comment]
Thanks @simonwashere! Please, could you send a PR?

**Comment by simonwashere** [comment]
I made a PR for this issue.

One other thought about textboxes, the multiline textbox seems to do word wrapping to the control width by inserting newlines into the text? I think this is a bad idea because the view layout shouldn't really change the data like that, and for instance the user might want to display the same text in a different width control later. A better solution would be to leave the text unchanged and do word wrapping only when it is rendered, you would need to have a DrawText() function which has a displayWidth parameter. Just a thought anyway.

**Comment by raysan5** [comment]
Agree, `GuiTextBoxMulti()` requires a review... Actually, raylib implements `DrawTextRec()` with that functionality!

**Comment by raysan5** [comment]
Colisng this issue per https://github.com/raysan5/raygui/pull/37
