### ISSUE TITLE
Change GuiStyleProp propertyValue from int to unsigned int

### ISSUE THREAD

**Issue by tyqualters** [raysan5/raygui#360]
VERSION raylib 5.0 / raygui 4.0

raygui.h line 450
```c
typedef struct GuiStyleProp {
    unsigned short controlId;   // Control identifier
    unsigned short propertyId;  // Property identifier
    int propertyValue;          // Property value
} GuiStyleProp;
```

Requesting change `int propertyValue;` to `unsigned int propertyValue;`

```c
typedef struct GuiStyleProp {
    unsigned short controlId;   // Control identifier
    unsigned short propertyId;  // Property identifier
    unsigned int propertyValue;          // Property value
} GuiStyleProp;
```

Reason being that there is a possible narrowing conversion to MAX_INT, and C++ (unlike C) will throw a lot of errors when trying to use any of the default styles (e.g. _/styles/cyber/style_cyber.h_) because of this narrowing conversion. This change fixes that issue and allows C++ to build.

**Comment by raysan5** [comment]
@tyqualters I'm afraid it's not possible to change this type because some properties could have negative values, for example `TEXT_SPACING`.
