### ISSUE TITLE
Cursor was missing when compiled in PLATFORM_DRM when using raygui. 

### ISSUE THREAD

**Issue by VisionShilin** [raysan5/raygui#363]
Cursor was missing when compiled in PLATFORM_DRM when using raygui while mouse events were normal. e.g. examples/shapes/shapes_draw_rectangle_rounded.c .

**Comment by raysan5** [comment]
@VisionShilin This is as design, it's up to the user to draw some kind of graphic reference for the mouse because `PLATFORM_DRM` works over the kernel (no windowing system) and the mouse cursor is provided by the windowing system.
