### ISSUE TITLE
Calling GuiLoadStyle() with enefete/sunny causes assertion fail in raylib

### ISSUE THREAD

**Issue by Zentrom** [raysan5/raygui#364]
Calling either of these...
```c++
GuiLoadStyle("Resources/style_sunny.rgs");
GuiLoadStyle("Resources/style_enefete.rgs");
``` 
causes an assertion fail in raylib:
![Képkivágás](https://github.com/raysan5/raygui/assets/26492517/504dba72-f157-44b4-a082-9db17462cde3)

All of the other styles work fine. Also, these styles work aswell with the uncompressed font files("style_sunny.old.rgs" and "style_enefete,old.rgs")

I used vcpkg to add raylib and raygui to my MSVC project, which currently installs raylib 5.0 and raygui 4.0

**Comment by raysan5** [comment]
Reviewed in raylib.
