### ISSUE TITLE
[Feature Request] Keyboard Navigation

### ISSUE THREAD

**Issue by ssoher** [raysan5/raygui#385]
It would be a nice addition if user could move between controls with Tab and Shift+Tab. Right now we have to use mouse and it slows down the workflow a lot when you have to edit multiple value boxes for example.

**Comment by raysan5** [comment]
I'm afraid supporting mouse navigation with controls "focus" would imply keeping some states and unique controls identifiers, that's against the purely immediate-mode nature of raygui. There could be some work-arounds but it would imply a considerable redesign of the library to support it.

**Comment by ssoher** [comment]
![cat-sad](https://github.com/raysan5/raygui/assets/4283979/22494318-704f-4f70-97da-47e00c495666)
