### ISSUE TITLE
Documentation on the `rgs` format

### ISSUE THREAD

**Issue by LiamM32** [raysan5/raygui#398]
I would like some documentation on how the `.rgs` file format works.

This would be helpful for me implement the `GuiLoadStyleFromMemory` function in another language; in my case D.

**Comment by ssoher** [comment]
> I would like some documentation on how the `.rgs` file format works.
> 
> This would be helpful for me implement the `GuiLoadStyleFromMemory` function in another language; in my case D.

Already available here

https://github.com/raysan5/rguistyler/blob/63cd62d43abd4efe88b2b0dfe109c75bf6d41fa3/src/rguistyler.c#L2026

**Comment by raysan5** [comment]
Considering raygui and rGuiStyler are both open source projects, I think it's ok for now to keep the specs info there. Maybe in a future it can be moved somewhere else...
