### ISSUE TITLE
Provide additional controls

### ISSUE THREAD

**Issue by raysan5** [raysan5/raygui#4]
Right now raygui implements following controls:

 - [x] Label
 - [x] Button
 - [x] ImageButton
 - [x] ToggleButton
 - [x] ToggleGroup
 - [x] CheckBox
 - [x] ComboBox
 - [x] GroupBox
 - [x] TextBox
 - [x] Slider
 - [x] SliderBar
 - [x] ProgressBar
 - [x] Spinner
 - [x] ColorPicker (requires some review)

Here it is a possible list of additional controls:

 - [x] LabelButton
 - [x] ListView
 - [ ] TreeView
 - [x] ImageBox
 - [ ] ScrollPanel
 - [ ] Dialog
 - [x] MessageDialog
 - [ ] DatePicker

What do you think?

**Comment by data-man** [comment]
Tree control?

**Comment by raysan5** [comment]
Hi @data-man! Thanks for the answer! TreeView is a tough one... added! :)

**Comment by nicrf** [comment]
Navigation with gamepad?

**Comment by SuicidalMK** [comment]
TextBox with multi line support?

**Comment by raysan5** [comment]
Some ideas: https://en.wikipedia.org/wiki/Widget_(GUI)

**Comment by zhouxs1023** [comment]
The most application have menus, so this lib should add menus function!

**Comment by raysan5** [comment]
Opened two separate issues for [ScrollPanel](https://github.com/raysan5/raygui/issues/8) and [FileDialog](https://github.com/raysan5/raygui/issues/10). No plans to add additional controls at the moment.
