### ISSUE TITLE
Compile for Rapberry Pi 2B

### ISSUE THREAD

**Issue by colesnicov** [raysan5/raygui#400]
Hello. When was the last time you tested PLATFORM_RPI?
I just tried compiling it for Raspberry Pi 2B and it failed. To compile, I edited the line https://github.com/raysan5/raygui/blob/a3a0e86e215145c28726e6f469f13d0aa6647a5e/examples/Makefile#L340 in the examples/Makefile to 
```
LDLIBS = -lraylib -lGLESv2 -lEGL -lpthread -lrt -lm -ldrm -lgbm -ldl
```

EDIT:

#### Environment

RPI 2B, Raspberry OS LITE, Raylib 5.1-dev

**Comment by colesnicov** [comment]
It is necessary to correctly install the **touch library** according to the https://github.com/raysan5/raylib/wiki/Install-and-configure-Touchscreen-Drivers-(RPi) and then it works..

**Comment by raysan5** [comment]
@colesnicov Definitely it was a since since last time I looked into that Makefile... updated! Thanks!
