### ISSUE TITLE
missing .c file in src ?

### ISSUE THREAD

**Issue by Ronin15** [raysan5/raygui#403]
no .c file in src ? Or is that expected ?

**Comment by raysan5** [comment]
@Ronin15 Yes, it's expected. raygui is a single-file header-only library, this is a new trend from the last few-years to include the library implementation inside the .h for easy distribution and integration of C libraries. You can check `raygui.h` implementation section and raygui examples for usage.

**Comment by Ronin15** [comment]
@raysan5 Thanks for the reply I'll check it out. Mainly trying to get raygui into odin.
