### ISSUE TITLE
GuiTextBox Line Highlight is offset wrong in different text alignment modes

### ISSUE THREAD

**Issue by Skytrias** [raysan5/raygui#43]
In the gif you can see what happens when i switch modes. It also happens when the text box has a bigger width, so its not based on that.

![2019-07-08_22-53-31](https://user-images.githubusercontent.com/22886746/60842013-6e2b1780-a1d3-11e9-80dc-d051373894fd.gif)

**Comment by raysan5** [comment]
Yes, this requires review...

**Comment by raysan5** [comment]
@Skytrias Reviewed in commit https://github.com/raysan5/raygui/commit/b51ab5b0e7c2abf61fc2eeb568c773895b156f14. It should be ok now.
