### ISSUE TITLE
Implicit declaration of function 'TextToFloat', undefined reference to `TextToFloat'

### ISSUE THREAD

**Issue by 0ero-1ne** [raysan5/raygui#432]
Hi there. Trying to create program from example:
```
#define RAYGUI_IMPLEMENTATION

#include "raylib.h"
#include "raygui.h"

int main()
{
    InitWindow(400, 200, "raygui - controls test suite");
    SetTargetFPS(60);

    bool showMessageBox = false;

    while (!WindowShouldClose())
    {
        // Draw
        //----------------------------------------------------------------------------------
        BeginDrawing();
        ClearBackground(GetColor(GuiGetStyle(DEFAULT, BACKGROUND_COLOR)));

        if (GuiButton((Rectangle){24, 24, 120, 30}, "#191#Show Message"))
            showMessageBox = true;

        if (showMessageBox)
        {
            int result = GuiMessageBox((Rectangle){85, 70, 250, 100},
                                       "#191#Message Box", "Hi! This is a message!", "Nice;Cool");

            if (result >= 0)
                showMessageBox = false;
        }

        EndDrawing();
    }

    CloseWindow();
    return 0;
}
```

Compiling program with w64devkit:
`gcc main.c -o main -I"C:\raylib\raylib\src" -L"C:\raylib\raylib\src" -lraylib -lgdi32 -lwinmm -std=c99 -Wall -mwindows -lopengl32`

![image](https://github.com/user-attachments/assets/17508a83-955f-483c-8f1e-5eb157ba2026)

Did I miss any parameter or any library?

P.S. raygui.h file is in the raylib/raylib/src directory.

**Comment by into233** [comment]
I modified the code by making 
``` c
static float TextToFloat(const char *text) { ... } 
```
the first function in raygui.h, and it works for me now.

**Comment by 0ero-1ne** [comment]
> I modified the code by making
> 
> ```c
> static float TextToFloat(const char *text) { ... } 
> ```
> 
> the first function in raygui.h, and it works for me now.

Thank you very much, man!!!
But could you explain why it helped?

**Comment by raysan5** [comment]
TextToFloat() is provided in raylib 5.5-dev, that is the version that should be used with latest raygui.
