### ISSUE TITLE
`GuiButton()` stay in state `STATE_PRESSED` until we touch screen else where on Android

### ISSUE THREAD

**Issue by GreenSnakeLinux** [raysan5/raygui#434]
Hi,

For the GuiButton, on Windows the bevahiour is good, with the mouse the button is highlighted then go back to normal state but on Android the button stay highlighted when touch it and release, I need to touch the screen some where else to go back to normal state.
I have tried to used GuiSetState but no success

Thanks for your help

**Comment by raysan5** [comment]
@GreenSnakeLinux It seems this issue could be more related to raylib and the `rcore_android` backend than `raygui` itself.

**Comment by raysan5** [comment]
Closing as issue belongs to raylib.
