### ISSUE TITLE
Missing pixels on `DrawCircleV()` only with raygui

### ISSUE THREAD

**Issue by timtro** [raysan5/raygui#440]
In the following image, you will note that the circles (drawn with `DrawCircleV`) seem to be missing pixels.

![Screenshot from 2024-11-10 11-32-58](https://github.com/user-attachments/assets/006f7baf-aa96-4fb1-b1e8-426a2b66d571)

I am aware of the raylib issue [#3247](https://github.com/raysan5/raylib/issues/3247), but I don' think this is related because the problem wasn't there until I added the GUI elements, and goes away when I comment them out. See my main function below.
```C++
int main(void) {
  SetConfigFlags(FLAG_WINDOW_MAXIMIZED | FLAG_WINDOW_RESIZABLE
                 | FLAG_MSAA_4X_HINT);

  InitWindow(1920, 1080, "Spline Playground");
  SetTargetFPS(120);

  AppState app = []() {
    AppState s;
    s.cam = Camera2D{.offset =
                         Vector2(GetScreenWidth() / 2., GetScreenHeight() / 2.),
                     .target = Vector2(0, 0),
                     .rotation = 0,
                     .zoom = 50};
    return s;
  }();

  while (!WindowShouldClose()) {
    BeginDrawing();
    BeginMode2D(app.cam);
    ClearBackground(RAYWHITE);
    app.update_mouse_coordinates();
    app.update_camera();
    app.focused_point = std::nullopt;

    app.draw_2d_fullscreen_grid();
    app.draw_fps();
    app.draw_spline_points();

    // … input handling and state logic to determine what is drawn
    // …
    // …

    EndMode2D();

    // Problem goes away if I comment out the `GuiCheckBox`s.
    GuiCheckBox((Rectangle){12, 62, 20, 20}, "Draw Velocity Vectors",
                &app.draw_velocity);
    GuiCheckBox((Rectangle){12, 60 + 25, 20, 20}, "Draw Acceleration Vectors",
                &app.draw_acceleration);
    GuiCheckBox((Rectangle){12, 60 + 50, 20, 20}, "Draw Curvature Cone",
                &app.draw_curvature_comb);

    EndDrawing();
  }

  CloseWindow();  // Close window and OpenGL context

  return 0;
}
```

This may well be a mistake I'm making and not a bug. Apologies in advance if it is my fault.

**Comment by raysan5** [comment]
@timtro did you try removing `FLAG_MSAA_4X_HINT`? I think issue could be related to it and unfortunately mostly dependant on GPU/drivers, so, very difficult to address... An alternative solution is using a texture with a circle.

**Comment by raysan5** [comment]
@timtro The issue is related to how raylib manages triangles and how the driver softens the "connection" between **individual** triangles, not-connected as a triangle-strip. It's tricky and not easy to address, also dependant on GPU and driver. A possible solution is using a texture with a circle instead of a triangles-based circle shape.
