### ISSUE TITLE
Questions about `GuiProgressBar` value parameter mutability

### ISSUE THREAD

**Issue by clembu** [raysan5/raygui#444]
## Context
Here's the signature for `GuiProgressBar` as of today (November 2024):
https://github.com/raysan5/raygui/blob/1e03efca48c50c5ea4b4a053d5bf04bad58d3e43/src/raygui.h#L748

In September 2023, in the 4.0 release, a lot of control drawing functions were changed to take value parameters by reference, including `GuiProgressBar`:
https://github.com/raysan5/raygui/blob/1e03efca48c50c5ea4b4a053d5bf04bad58d3e43/src/raygui.h#L178

I was curious why, because we usually do not tend to think of a progressbar as an interactive display, it is usually informative only in nature, and definitely shouldn't allow the user to modify "how much progress has been made," by just dragging a knob on the progress bar. So I took a look inside.

The `value` parameter, taken as reference, is modified twice inside the function:
- once to set it to 50% in case it is a null pointer
https://github.com/raysan5/raygui/blob/1e03efca48c50c5ea4b4a053d5bf04bad58d3e43/src/raygui.h#L3254-L3255
Though as one can see, this is *replacing* the local pointer, not modifying the float it points to (because it points to nothing). This is only done so that `value` is a valid non-null pointer for the rest of the function.
- once to clamp it down to the maximum value if too high
https://github.com/raysan5/raygui/blob/1e03efca48c50c5ea4b4a053d5bf04bad58d3e43/src/raygui.h#L3262-L3264

## Questions
The first thing I noticed was that, while the value is clamped down to the `maxValue`, **it is never clamped up to the `minValue`.**
Is that a design choice, or an oversight?

But my main question is: **why do this by reference at all?**

I understand wanting some unified interface with other functions like `GuiSlider`, but it doesn't sound like a good reason enough to me to make an informative control able to modify the information it displays. It forces the calling code to take that into account when using a progress bar, and make sure a pointer exists and stays valid during the whole function, so one cannot just call `GuiProgressBar(bounds, done / todo, 0f, 1f)`. 

In itself it is not a big deal, I am just curious. The only practical reason to clamp the `value` down to the `maxValue` is to make the width and sizes computations correct, it has no reason that I can think of to reflect back to the calling code.

**Comment by raysan5** [comment]
@clembu Not clamping to `minValue` was a design choice because it was expected to be managed by user, but it can be added.

About getting the parameter by reference, it requires to be updated in case it needs to be clamped. And obviously the unified interface, that's a very important reason to me.
