### ISSUE TITLE
GuiXXX suppert Texture2D ?

### ISSUE THREAD

**Issue by sdragonx** [raysan5/raygui#445]
or add GuiImageButton(), GuiImage().

SetGuiBackground(Texture2D).

**Comment by raysan5** [comment]
@sdragonx Adding a `Texture2D` control to `raygui` would create a hard-coupling with `raylib`, I prefer let the users manage it on user-side with raylib directly.

**Comment by sdragonx** [comment]
raygui's controls cannot change the background image, for example, if you want to use the image button. If users only use raylib to implement it themselves or other libraries, what is the significance of raygui's existence...
