### ISSUE TITLE
GuiWindow header size with border

### ISSUE THREAD

**Issue by anatagawa** [raysan5/raygui#48]
Header size dont take the border size. can see taht with the cross at top right

with border size of 1 
![alt text](http://screens.anatagawa.fr/screen_2019-08-17_12-29-07.png "Border at 1")

with border size of 2
![alt text](http://screens.anatagawa.fr/screen_2019-08-17_12-34-12.png "Border at 2")

**Comment by raysan5** [comment]
REviewed in latest commits (https://github.com/raysan5/raygui/commit/4ec4419635a4126d5451323dd6212667089cee3c).
