### ISSUE TITLE
Layout System?

### ISSUE THREAD

**Issue by hbiblia** [raysan5/raygui#50]
Seria bueno agregar un sistema de layout para ahorrar trabajo de calculo.

Estoy trabajando en un proyecto y creo que es incomodo hacer esto manual y creo que con un layout system se podría mejorar mucho. 

Esto lo escribí para ahorrar un poco...

```
void gui_main_toolbar()
{
    int screenWidth = GetScreenWidth();
    Rectangle toolbar_bounds = {0,0, screenWidth, 50};

    GuiPanel(toolbar_bounds);
    gui_layout_row_begin(&toolbar_bounds);
    {
        gui_layout_row_static(80, 30);
        gui_layout_row_offset(5, 10);
        if(gui_button("New")){}
        if(gui_button("Save")){}
        
        gui_space_horizontal();

        if(gui_button("Tile")){}
        if(gui_button("Actor")){}
        if(gui_button("Animate2d")){}
        if(gui_button("Camera")){}
    }
    gui_layout_row_end();
}
```

![Captura de pantalla (34)](https://user-images.githubusercontent.com/1939353/63738555-1f574100-c858-11e9-8b2a-3a6f14f047a6.png)

**Comment by raysan5** [comment]
Already thought about that, other libraries like Nuklear use this scheme. Unfortunately, it will require a complete redesign of the library to support this feature. Not planned at this moment.

I created [rGuiLayout()](https://raylibtech.itch.io/rguilayout) tool to minimize this problem. It's not automatic layouting but you can create the layout in a visual way.
