### ISSUE TITLE
font.recs

### ISSUE THREAD

**Issue by KevinMagnifico260** [raysan5/raygui#56]
When i'm tried to compile i received error
The issued in this project is "font.recs" has no member named

**Comment by raysan5** [comment]
@KevinMagnifico260 you should use `raylib 2-6-dev`, compiled manually from GitHub master branch, `struct Font` has changed.

**Comment by KevinMagnifico260** [comment]
Thanl you sir

    On Wednesday, October 16, 2019, 5:38:18 AM GMT+8, Ray <notifications@github.com> wrote:  
 
 
@KevinMagnifico260 you should use raylib 2-6-dev, compiled manually from GitHub master branch, struct Font has changed.

**Comment by Quantumplation** [comment]
@raysan5 I'm having difficulty building raylib off master.  Would it be possible to either provide a beta raylib 2.6 installer, or a release for this project which is compatible with raylib 2.5?
