### ISSUE TITLE
Compiler Warnings

### ISSUE THREAD

**Issue by smalls12** [raysan5/raygui#61]
Hello,
I've started using raygui and noticed some immediate compile warnings.

In my projects I compile with cmake and set:
`set( CMAKE_CXX_FLAGS " -g -Wall -Wextra -fPIC -std=c++17 " )`

This will produce quite a few warnings which I think can be fixed pretty easily.

Should this be addressed?

Thanks :)

**Comment by raysan5** [comment]
what warning do you get? you can send a PR, feel free! 😄

**Comment by raysan5** [comment]
Just for reference, warning were related to `fread()` not checking for correct data reading. For the moment I'm keeping it this way.

**Comment by smalls12** [comment]
Going to reopen, going to address the other warnings I found.

**Comment by raysan5** [comment]
@smalls12 I'm afraid I'm neither merging this change, sorry.
