### ISSUE TITLE
C++ Header Design

### ISSUE THREAD

**Issue by smalls12** [raysan5/raygui#62]
Posting here for clarification, and for anyone else that is trying to overcome this hurdle.

I have a C++ application where the GUI window is launched in main() and then manipulated via other C++ objects via raygui.

Originally, I was getting duplicate definition errors due to the way I was including raygui in all of my code, as seen below:
```
extern "C" {
#include "raylib.h"

#define RAYGUI_IMPLEMENTATION
#include "raygui.h"
}
```
The "correct" implementation for this should be to use the above within main(), and then use the following everywhere else:
```
extern "C" {
#include "raylib.h"

#define RAYGUI_STATIC
#include "raygui.h"
}
```
Is this "correct" ?

**Comment by smalls12** [comment]
Should also note that this also creates a slew of compiler warnings.

**Comment by raysan5** [comment]
It should probably be redesigned...

**Comment by smalls12** [comment]
I don't think it would be too hard to keep the definitions in the header, and build a library for the actual implementation.
This would break the header only design, but in the long run might be more maintainable.
This would also follow what raylib does.

**Comment by raysan5** [comment]
@smalls12 I redesigned the functions definition settings in commit https://github.com/raysan5/raygui/commit/09d583687ab8025f2a1f5c316198c2147e6ddaaa.

Now it should work as expected:
```c
#include "raylib.h"

#define RAYGUI_IMPLEMENTATION
//#define RAYGUI_STATIC    // Only if you want to keep raygui functionality internal to current module
#include "raygui.h"
```

**Comment by smalls12** [comment]
Okay appears to be working now.
I do get the following warning though.
```
In file included from /src/scratch/blokus/src/StartScreen.cpp:3:0:
/src/staging/usr/include/raygui.h:144:0: warning: "RAYGUIDEF" redefined
         #define RAYGUIDEF extern "C"    // Functions visible from other files (no name mangling of functions in C++)
 
/src/staging/usr/include/raygui.h:137:0: note: this is the location of the previous definition
 #define RAYGUIDEF               // We are building or using raygui as a static library (or Linux shared library)

```

**Comment by raysan5** [comment]
Yeah, I simplified the conditions to work better but it involved redefining the define when required.

**Comment by daidalo-s** [comment]
Hi, i'm commenting on this closed issue since i'm having a similar problem with the original comment.
Like in the first comment, i'm developing a C++ application where i wrap all the different raygui elements into it's own class (I'm a beginner so sorry if this is a very stupid questions).
I'm downloading the latest raylib version using CMake
```
FetchContent_Declare(
        raylib
        GIT_REPOSITORY "https://github.com/raysan5/raylib.git"
        GIT_TAG "master"
        GIT_PROGRESS TRUE
)
FetchContent_MakeAvailable(raylib)
```
and i have copied both the raylib and the raygui header files into a folder in my project i called ```include```.
Than in my main file (```main.cpp```) i have
```c++
#include "./include/raylib.h"
#define RAYGUI_IMPLEMENTATION
#include "./include/raygui.h"
#include "./include/button.hpp"
```
and in my ```button.h```
```c++
#include "./raylib.h"
#include "./raygui.h"
```
The error i'm getting is 
```
In file included from /Users/lorenzo/Developer/battaglia_navale/src/main.cpp:7:
In file included from /Users/lorenzo/Developer/battaglia_navale/src/./include/button.hpp:6:
/Users/lorenzo/Developer/battaglia_navale/src/./include/raygui.h:1072:21: error: redefinition of 'guiIcons'
static unsigned int guiIcons[RAYGUI_ICON_MAX_ICONS*RAYGUI_ICON_DATA_ELEMENTS] = {
```
Looking at the ```raygui.h```file i can see the problem, there are parts of code that are not guarded from multiple inclusions. Am i misinterpreting the warning 
```
NOTE: raygui is a single-file header-only library (despite its internal dependency on raylib), so, functions definition AND implementation reside in the same file raygui.h, when including raygui.h in a module, RAYGUI_IMPLEMENTATION must be previously defined to include the implementation part of raygui.h BUT only in one compilation unit, other modules could also include raygui.h but RAYGUI_IMPLEMENTATION must not be defined again.
```
in the raygui README?

**Comment by raysan5** [comment]
@daidalo-s The solution I use for those cases is:
```c
#include "./include/raylib.h"
#define RAYGUI_IMPLEMENTATION
#include "./include/raygui.h"
#undef RAYGUI_IMPLEMENTATION                // Avoid including raygui implementation again
```

**Comment by daidalo-s** [comment]
Thanks a lot! This worked!
