### ISSUE TITLE
ricons delimiter

### ISSUE THREAD

**Issue by anatagawa** [raysan5/raygui#67]
The right way to put ricon is

`"#120#` 

if you put `#120` it works if it is the last draw.

Ricon doesnt take the last delimiter correctly.

you can put `#120 ` or `#120a` to show the icon.
or put `#120#123` or `#120a123` to show the icon + 123 after.

**Comment by raysan5** [comment]
Key function to review: `GetTextIcon()`, just for reference.

**Comment by raysan5** [comment]
Done. ;)
