### ISSUE TITLE
RAYGUI_STANDALONE doesn't seem to actually work?

### ISSUE THREAD

**Issue by moon-chilled** [raysan5/raygui#68]
I was attracted to raygui because it seemed like it would be easier to integrate with my engine than some other imgui implementations, since I could provide the drawing functions myself.

I started off with a simple stub looking like [this](http://sprunge.us/pqFilt?c).  (All the seemingly pointless indirections are necessary because the engine isn't written in c.)

However, even that fails to compile, with [these errors](http://ix.io/281P).

**Comment by raysan5** [comment]
@moon-chilled I'm reviewing it and setting up an example.

**Comment by raysan5** [comment]
raygui reviewed and standalone example added in commit https://github.com/raysan5/raygui/commit/146068751c0328654dc695ffd668ad2fb6435754. Please let me know if it works for your custom backend.

**Comment by moon-chilled** [comment]
Thank you for the changes!  I haven't had a chance yet to actually test it out yet (been quite busy), but can confirm there are no compilation errors.  I only have one request: can the `id` member of `Texture2D` be changed to `void*`?  All ok if not, but this would make it easier for me to implement as I can make it a pointer to an in-engine font object.  And none of the existing code would break since all they check for is if id is not 0.

**Comment by raysan5** [comment]
Hi @moon-chilled, I'm still looking for a better way to deal with Texture2D/Fonts structs data in `raygui`, I know at this moment it's quite coupled to `raylib`.
