### ISSUE TITLE
Ctrl + Z does not destroy a newly created control

### ISSUE THREAD

**Issue by EJSainz** [raysan5/raygui#7]
After creating a new control, pressing Ctrl + Z won't destroy it, but will place it where the last deleted control was.

How to reproduce:
-Open rGuiLayout
-Create a new control (probably any type will do) at any point
-Delete the control (get close with the mouse - it turns red - then press delete)
-Create a new control (probably any type will do) at any different point from the previous one
-Press Ctrl+Z
-Notice the secondly created control has now moved the position where the first control was

**Comment by raysan5** [comment]
Thanks for the feedback @EJSainz, unfortunately CTRL+Z is quite limited at this moment. Implementing a proper CTRL+Z would require a big amount of work and is not viable at this moment.

Just closing this issue for the moment.
