### ISSUE TITLE
Promote GuiColorPanel, GuiColorBarAlpha and GuiColorBarHue ?

### ISSUE THREAD

**Issue by woollybah** [raysan5/raygui#74]
The functions`GuiColorPanel`, `GuiColorBarAlpha` and `GuiColorBarHue` are parts of the color picker, and available to use if you dig into the header, but they are not directly part of the "api".

However, `GuiColorBarAlpha` is actually used in the `controls_test_suite` example.

Is it worth promoting them to the api proper?

**Comment by raysan5** [comment]
@woollybah I'm not specially happy with those controls but I exposed it to the API.
