### ISSUE TITLE
Compiling into Raylib.dll

### ISSUE THREAD

**Issue by Bambofy** [raysan5/raygui#75]
Hi,

I'm trying to use this library to make a game using C# - https://github.com/ChrisDill/Raylib-cs

With it i want to use the RayGUI functions too but i don't think raygui is compiled into the raylib.dll given in the releases. How do i go about compiling raygui into the standalone raylib?

Thanks!
Richard

**Comment by raysan5** [comment]
Hi @Bambofy, actually I think @ChrisDill did some work on `raygui` integration with C#. Maybe he can provide more info on this issue.

**Comment by ChrisDill** [comment]
@Bambofy There have been a lot of changes to Raylib-cs preparing for 3.0 but I have not merged into the master branch yet so you should wait until then to use Raygui.cs.

There were changes made to the raylib to make it easier to build into raylib but it was not a simple process so I changed Raylib-cs to to use a seperate library instead. On windows this would be raygui.dll.

Currently, raygui does not include prebuilt libraries so you will need to compile it yourself. I would like to help add that though so I could include them with my next release which should make things easier for new users.

Hope this helps!

**Comment by Bambofy** [comment]
> 
> 
> @Bambofy There have been a lot of changes to Raylib-cs preparing for 3.0 but I have not merged into the master branch yet so you should wait until then to use Raygui.cs.
> 
> There were changes made to the raylib Makefile to make it easier to build into raylib but it was not a simple process so I changed Raylib-cs to to use a seperate library instead. On windows this would be raygui.dll.
> 
> Currently, raygui does not include prebuilt libraries so you will need to compile it yourself. I would like to help add them though so I could include them with my next release which should make things easier for new users.
> 
> Hope this helps!

Thanks for the replies :) I'm not sure how to compile this raygui repository, is there any documentation for it?

**Comment by raysan5** [comment]
@Bambofy `raygui` is designed as single-file header-only library, to use it just include it in your project, you can check `src/raygui.h` header information for details on usage.
