### ISSUE TITLE
Cmake file for building dynamic library.

### ISSUE THREAD

**Issue by Bambofy** [raysan5/raygui#77]
Hello, there is no cmake file for building raygui but i've made one here:

```
cmake_minimum_required(VERSION 3.0.0)

project (raygui)

file(GLOB ALL_SRCS
        "${CMAKE_CURRENT_SOURCE_DIR}/src/*.c"
        )

add_library(raygui SHARED ${ALL_SRCS})
target_include_directories(raygui PUBLIC ${CMAKE_CURRENT_SOURCE_DIR}/src)

###########################
# Add the Raylib library. #
###########################
find_path(RAYLIB_INCLUDE_DIRS RAYLIB)
find_library(RAYLIB_LIBRARIES RAYLIB)
target_link_libraries(raygui ${RAYLIB_LIBRARIES})
target_include_directories(raygui PRIVATE ${RAYLIB_INCLUDE_DIRS})
```

Additionally a file called raygui.c must be in the /src/ directory with these contents:
```
#define RAYGUI_IMPLEMENTATION
#include "raygui.h"
```

**Comment by Bambofy** [comment]
Also, i've created the LuaJIT bindings for raylib and raygui you can find them here:
https://github.com/Bambofy/LuaJIT-Raylib

**Comment by raysan5** [comment]
Thanks for the CMake but this is a very small single-file header-only portable library, not intended to be builded as a separate library.
