### ISSUE TITLE
CMake: Clean up CMakeLists.txt conditionals

### ISSUE THREAD

**Issue by RobLoach** [raysan5/raygui#89]
@stanczyk4 on Discord mentioned referencing individual features from the CMake. Would be good to split it into different directories.

**Comment by raysan5** [comment]
@RobLoach that's the reason I'm against CMake build system... why it needs to be splitted all around? The build system consist of more files in the repo than the code itself??? I don't like it.

**Comment by RobLoach** [comment]
It could live in the same file. Just need to clean up the conditionals.
