### ISSUE TITLE
build failed on ubuntu 18

### ISSUE THREAD

**Issue by wtjcn** [raysan5/raygui#91]
build failed on ubuntu 18, it seems lack some library in cmake file, my fix is add some :
 
        target_link_libraries(${example_name} PUBLIC raylib raygui pthread Xi GLU GL drm Xdamage  X11-xcb xcb-glx xcb-dri2 xcb-dri3
		    xcb-present xcb-sync xshmfence glfw3 rt m dl Xrandr Xinerama
		    Xxf86vm Xcursor Xext Xrender Xfixes X11 xcb Xau Xdmcp png)

**Comment by raysan5** [comment]
@wtjcn thanks for reporting, unfortunately I'm not supporting CMake build system, you can try provided Makefiles instead, they should work ok.
