### ISSUE TITLE
Feature Request: Implement Docking just like IMGui

### ISSUE THREAD

**Issue by sparkskapil** [raysan5/raygui#93]
This is a feature request for implementing Docking feature.
This feature is present in IMGui docking branch.

**Comment by raysan5** [comment]
hi @sparkskapil! I'm afraid auto-layouting and docking is out-of-scope for this project.

**Comment by sparkskapil** [comment]
Is it possible to use Dear ImGUI with Raylib?
If yes can you please let me know some sources which can help.

**Comment by raysan5** [comment]
@sparkskapil I haven't tested it but here are a couple of projects integrating it: 
 - https://github.com/osom8979/tbag/tree/master/libtbag/ray
 - https://github.com/oswjk/raylib-imgui-template/tree/master/%7B%7Bcookiecutter.project_name%7D%7D/src/external

**Comment by sparkskapil** [comment]
Thanks @raysan5  
I'll have a look at these projects.
