### ISSUE TITLE
GuiTextBoxMulti can't handle strings that contain no spaces, or that contain space-free sequences wider than bound's width

### ISSUE THREAD

**Issue by kamisori** [raysan5/raygui#94]
https://github.com/raysan5/raygui/blob/3e61557f251c5c64ed002081870434e9dbaa7ba7/src/raygui.h#L1769 and following.

If there is no space in `text`, `lastSpacePos` is never set to anything but 0. Because of this index `i` gets reset to 0 and an infinite loop ensues.

**Comment by raysan5** [comment]
@kamisori Can this issue be closed?
