### ISSUE TITLE
GuiTextBoxMulti cursor placement is off

### ISSUE THREAD

**Issue by kamisori** [raysan5/raygui#96]
https://github.com/raysan5/raygui/blob/3e61557f251c5c64ed002081870434e9dbaa7ba7/src/raygui.h#L1789

...by exactly one pixel vertically per line with:
:text-size:10
:text-inner-padding:4
:border-width:1
:text-spacing:1

:text-inner-padding:5 makes the cursor lag behind a character per line starting in line 3
still trying to figure this out

**Comment by raysan5** [comment]
@kamisori Thanks for working on those improvements!

**Comment by Julianiolo** [comment]
@raysan5, @kamisori  I fixed it, added a PR. I didn't know there was already somebody working on that problem :o

**Comment by raysan5** [comment]
I'm afraid `GuiTextBoxMulti()` has been redesigned from scratch.
