### ISSUE TITLE
Unicode support? 

### ISSUE THREAD

**Issue by AlbertoFrancoDD** [raysan5/raygui#99]
Hi! I was wondering it you have any plan to include unicode support for raygui. At the moment in our app if we try to input anything non-ascii it will not display it properly. 

Thanks a lot, 
Alberto

**Comment by raysan5** [comment]
Hi @AlbertoFrancoDD, actually `raygui` supports Unicode.

`raygui` uses internally `raylib` `DrawTextEx()` function that supports Unicode but it requires a font including Unicode characters required. Default `raygui` font just includes basic ASCII charset but a custom font with all required characters could be set with `GuiSetFont()`. It must be previously loaded with raylib function `LoadFontEx()`.

Just make sure all the strings used are codifies as UTF-8 (simply save your code files as UTF-8).

**Comment by AlbertoFrancoDD** [comment]
Hi @raysan5 
it is true, the writing of the fonts is handled so I can display unicode strings but the input is not. If I try to input anything (I am working on windows atm) the input is in the local code page (sic) and not unicode, even if the project is set with unicode support. So the strings will end up wrong. I can handle this on my side by diffing the string and converting the non-UTF part but it would be cool to have it out of the box. The problem here is that `GetKeyPressed()` will return you the codepoint for the key stroke. 

The change would be simple, using CodepointToUtf8 instead of directly casting ints to chars in the implementation of text boxes. 

Hope this helps

**Comment by raysan5** [comment]
@AlbertoFrancoDD oh, I see! Sure, I can do that! :)

**Comment by AlbertoFrancoDD** [comment]
Cool @raysan5! Thanks a lot!

**Comment by raysan5** [comment]
@AlbertoFrancoDD Please, let me know if it works.
